from sqlalchemy import Column, String, DECIMAL, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.dialects.mysql import LONGTEXT
all_tables = ['ASHAREBALANCESHEET', 'ASHARECAPITALIZATION', 'ASHARECASHFLOW', 'ASHAREDESCRIPTION', 'ASHAREDIVIDEND', 'ASHAREFINANCIALINDICATOR', 'ASHAREFREEFLOAT', 'ASHAREINCOME', 'ASHAREINDUSTRIESCODE', 'ASHAREPROFITEXPRESS', 'ASHARERIGHTISSUE', 'CFUNDWINDINDEXCOMPONENT', 'CHINAMUTUALFUNDASSETPORTFOLIO', 'CHINAMUTUALFUNDNAV', 'CHINAMUTUALFUNDREPNAVPER', 'CHINAMUTUALFUNDSEATTRADING', 'CMFINDUSTRYPLATE', 'CMFIOPVNAV', 'CMFNAVOPERATIONRECORD', 'CMFTHEMECONCEPT', 'COMPINTRODUCTION', 'INDEXCONTRASTSECTOR']
Base = declarative_base()
metadata = Base.metadata


class ASHAREBALANCESHEET(Base):

    __tablename__ = 'ASHAREBALANCESHEET'

    ACC_EXP = Column(DECIMAL(20, 4), doc="预提费用")
    ACCOUNTS_PAYABLE = Column(DECIMAL(20, 4), doc="应付票据及应付账款")
    ACCOUNTS_RECEIVABLE = Column(DECIMAL(20, 4), doc="应收款项")
    ACCOUNTS_RECEIVABLE_BILL = Column(DECIMAL(20, 4), doc="应收票据及应收账款")
    ACCT_PAYABLE = Column(DECIMAL(20, 4), doc="应付账款")
    ACCT_RCV = Column(DECIMAL(20, 4), doc="应收账款")
    ACTING_TRADING_SEC = Column(DECIMAL(20, 4), doc="代理买卖证券款")
    ACTING_UW_SEC = Column(DECIMAL(20, 4), doc="代理承销证券款")
    ACTUAL_ANN_DT = Column(String(8), doc="实际公告日期")
    ADV_FROM_CUST = Column(DECIMAL(20, 4), doc="预收款项")
    AGENCY_BUS_ASSETS = Column(DECIMAL(20, 4), doc="代理业务资产")
    AGENCY_BUS_LIAB = Column(DECIMAL(20, 4), doc="代理业务负债")
    ANN_DT = Column(String(8), doc="公告日期")
    ASSET_DEP_OTH_BANKS_FIN_INST = Column(DECIMAL(20, 4), doc="存放同业和其它金融机构款项")
    BONDS_PAYABLE = Column(DECIMAL(20, 4), doc="应付债券")
    BORROW_CENTRAL_BANK = Column(DECIMAL(20, 4), doc="向中央银行借款")
    CAP_MRGN_PAID = Column(DECIMAL(20, 4), doc="存出资本保证金")
    CAP_RSRV = Column(DECIMAL(20, 4), doc="资本公积金")
    CAP_STK = Column(DECIMAL(20, 4), doc="股本")
    CASH_DEPOSITS_CENTRAL_BANK = Column(DECIMAL(20, 4), doc="现金及存放中央银行款项")
    CLAIMS_PAYABLE = Column(DECIMAL(20, 4), doc="应付赔付款")
    CLIENTS_CAP_DEPOSIT = Column(DECIMAL(20, 4), doc="客户资金存款")
    CLIENTS_RSRV_SETTLE = Column(DECIMAL(20, 4), doc="客户备付金")
    CNVD_DIFF_FOREIGN_CURR_STAT = Column(DECIMAL(20, 4), doc="外币报表折算差额")
    COMP_TYPE_CODE = Column(String(2), doc="公司类型代码")
    CONST_IN_PROG = Column(DECIMAL(20, 4), doc="在建工程")
    CONST_IN_PROG_TOT = Column(DECIMAL(20, 4), doc="在建工程(合计)(元)")
    CONSUMPTIVE_BIO_ASSETS = Column(DECIMAL(20, 4), doc="消耗性生物资产")
    CONTRACT_LIABILITIES = Column(DECIMAL(20, 4), doc="合同负债")
    CONTRACTUAL_ASSETS = Column(DECIMAL(20, 4), doc="合同资产")
    CRNCY_CODE = Column(String(10), doc="货币代码")
    CUST_BANK_DEP = Column(DECIMAL(20, 4), doc="吸收存款")
    DEBT_INVESTMENT = Column(DECIMAL(20, 4), doc="债权投资(元)")
    DEFERRED_EXP = Column(DECIMAL(20, 4), doc="待摊费用")
    DEFERRED_INC = Column(DECIMAL(20, 4), doc="递延收益")
    DEFERRED_INC_NON_CUR_LIAB = Column(DECIMAL(20, 4), doc="递延收益-非流动负债")
    DEFERRED_TAX_ASSETS = Column(DECIMAL(20, 4), doc="递延所得税资产")
    DEFERRED_TAX_LIAB = Column(DECIMAL(20, 4), doc="递延所得税负债")
    DEPOSIT_RECEIVED = Column(DECIMAL(20, 4), doc="存入保证金")
    DEPOSIT_RECEIVED_IB_DEPOSITS = Column(DECIMAL(20, 4), doc="吸收存款及同业存放")
    DERIVATIVE_FIN_ASSETS = Column(DECIMAL(20, 4), doc="衍生金融资产")
    DERIVATIVE_FIN_LIAB = Column(DECIMAL(20, 4), doc="衍生金融负债")
    DVD_PAYABLE = Column(DECIMAL(20, 4), doc="应付股利")
    DVD_PAYABLE_INSURED = Column(DECIMAL(20, 4), doc="应付保单红利")
    DVD_RCV = Column(DECIMAL(20, 4), doc="应收股利")
    EMPL_BEN_PAYABLE = Column(DECIMAL(20, 4), doc="应付职工薪酬")
    FIN_ASSETS_AVAIL_FOR_SALE = Column(DECIMAL(20, 4), doc="可供出售金融资产")
    FIN_ASSETS_COST_SHARING = Column(DECIMAL(20, 4), doc="以摊余成本计量的金融资产")
    FIN_ASSETS_FAIR_VALUE = Column(DECIMAL(20, 4), doc="以公允价值计量且其变动计入其他综合收益的金融资产")
    FIX_ASSETS = Column(DECIMAL(20, 4), doc="固定资产")
    FIX_ASSETS_DISP = Column(DECIMAL(20, 4), doc="固定资产清理")
    FUND_SALES_FIN_ASSETS_RP = Column(DECIMAL(20, 4), doc="卖出回购金融资产款")
    GOODWILL = Column(DECIMAL(20, 4), doc="商誉")
    HANDLING_CHARGES_COMM_PAYABLE = Column(DECIMAL(20, 4), doc="应付手续费及佣金")
    HELD_TO_MTY_INVEST = Column(DECIMAL(20, 4), doc="持有至到期投资")
    HFS_ASSETS = Column(DECIMAL(20, 4), doc="持有待售的资产")
    HFS_SALES = Column(DECIMAL(20, 4), doc="持有待售的负债")
    INCL_PLEDGE_LOAN = Column(DECIMAL(20, 4), doc="其中:质押借款")
    INCL_SEAT_FEES_EXCHANGE = Column(DECIMAL(20, 4), doc="其中:交易席位费")
    INDEPENDENT_ACCT_ASSETS = Column(DECIMAL(20, 4), doc="独立账户资产")
    INDEPENDENT_ACCT_LIAB = Column(DECIMAL(20, 4), doc="独立账户负债")
    INSURED_DEPOSIT_INVEST = Column(DECIMAL(20, 4), doc="保户储金及投资款")
    INSURED_PLEDGE_LOAN = Column(DECIMAL(20, 4), doc="保户质押贷款")
    INT_PAYABLE = Column(DECIMAL(20, 4), doc="应付利息")
    INT_RCV = Column(DECIMAL(20, 4), doc="应收利息")
    INTANG_ASSETS = Column(DECIMAL(20, 4), doc="无形资产")
    INVENTORIES = Column(DECIMAL(20, 4), doc="存货")
    INVEST_REAL_ESTATE = Column(DECIMAL(20, 4), doc="投资性房地产")
    LEASE_LIAB = Column(DECIMAL(20, 4), doc="租赁负债")
    LENDING_FUNDS = Column(DECIMAL(20, 4), doc="融出资金")
    LESS_TSY_STK = Column(DECIMAL(20, 4), doc="减:库存股")
    LIAB_DEP_OTH_BANKS_FIN_INST = Column(DECIMAL(20, 4), doc="同业和其它金融机构存放款项")
    LIFE_INSUR_RSRV = Column(DECIMAL(20, 4), doc="寿险责任准备金")
    LOANS_AND_ADV_GRANTED = Column(DECIMAL(20, 4), doc="发放贷款及垫款")
    LOANS_OTH_BANKS = Column(DECIMAL(20, 4), doc="拆入资金")
    LOANS_TO_OTH_BANKS = Column(DECIMAL(20, 4), doc="拆出资金")
    LONG_TERM_DEFERRED_EXP = Column(DECIMAL(20, 4), doc="长期待摊费用")
    LONG_TERM_EQY_INVEST = Column(DECIMAL(20, 4), doc="长期股权投资")
    LONG_TERM_REC = Column(DECIMAL(20, 4), doc="长期应收款")
    LT_BORROW = Column(DECIMAL(20, 4), doc="长期借款")
    LT_HEALTH_INSUR_V = Column(DECIMAL(20, 4), doc="长期健康险责任准备金")
    LT_PAYABLE = Column(DECIMAL(20, 4), doc="长期应付款")
    LT_PAYABLE_TOT = Column(DECIMAL(20, 4), doc="长期应付款(合计)(元)")
    LT_PAYROLL_PAYABLE = Column(DECIMAL(20, 4), doc="长期应付职工薪酬")
    MINORITY_INT = Column(DECIMAL(20, 4), doc="少数股东权益")
    MONETARY_CAP = Column(DECIMAL(20, 4), doc="货币资金")
    MRGN_PAID = Column(DECIMAL(20, 4), doc="存出保证金")
    NON_CUR_ASSETS_DUE_WITHIN_1Y = Column(DECIMAL(20, 4), doc="一年内到期的非流动资产")
    NON_CUR_LIAB_DUE_WITHIN_1Y = Column(DECIMAL(20, 4), doc="一年内到期的非流动负债")
    NOTES_PAYABLE = Column(DECIMAL(20, 4), doc="应付票据")
    NOTES_RCV = Column(DECIMAL(20, 4), doc="应收票据")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OIL_AND_NATURAL_GAS_ASSETS = Column(DECIMAL(20, 4), doc="油气资产")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    OTH_ASSETS = Column(DECIMAL(20, 4), doc="其他资产")
    OTH_CUR_ASSETS = Column(DECIMAL(20, 4), doc="其他流动资产")
    OTH_CUR_LIAB = Column(DECIMAL(20, 4), doc="其他流动负债")
    OTH_LIAB = Column(DECIMAL(20, 4), doc="其他负债")
    OTH_NON_CUR_ASSETS = Column(DECIMAL(20, 4), doc="其他非流动资产")
    OTH_NON_CUR_LIAB = Column(DECIMAL(20, 4), doc="其他非流动负债")
    OTH_PAYABLE = Column(DECIMAL(20, 4), doc="其他应付款")
    OTH_PAYABLE_TOT = Column(DECIMAL(20, 4), doc="其他应付款(合计)(元)")
    OTH_RCV = Column(DECIMAL(20, 4), doc="其他应收款")
    OTH_RCV_TOT = Column(DECIMAL(20, 4), doc="其他应收款(合计)（元）")
    OTHER_COMP_INCOME = Column(DECIMAL(20, 4), doc="其他综合收益")
    OTHER_DEBT_INVESTMENT = Column(DECIMAL(20, 4), doc="其他债权投资(元)")
    OTHER_EQUITY_INVESTMENT = Column(DECIMAL(20, 4), doc="其他权益工具投资(元)")
    OTHER_EQUITY_TOOLS = Column(DECIMAL(20, 4), doc="其他权益工具")
    OTHER_EQUITY_TOOLS_P_SHR = Column(DECIMAL(20, 4), doc="其他权益工具:优先股")
    OTHER_ILLIQUIDFINANCIAL_ASSETS = Column(DECIMAL(20, 4), doc="其他非流动金融资产(元)")
    OTHER_SUSTAINABLE_BOND = Column(DECIMAL(20, 4), doc="其他权益工具:永续债(元)")
    OUT_LOSS_RSRV = Column(DECIMAL(20, 4), doc="未决赔款准备金")
    PAYABLE_TO_REINSURER = Column(DECIMAL(20, 4), doc="应付分保账款")
    PAYABLES = Column(DECIMAL(20, 4), doc="应付款项")
    PRECIOUS_METALS = Column(DECIMAL(20, 4), doc="贵金属")
    PREM_RCV = Column(DECIMAL(20, 4), doc="应收保费")
    PREM_RECEIVED_ADV = Column(DECIMAL(20, 4), doc="预收保费")
    PREPAY = Column(DECIMAL(20, 4), doc="预付款项")
    PRODUCTIVE_BIO_ASSETS = Column(DECIMAL(20, 4), doc="生产性生物资产")
    PROJ_MATL = Column(DECIMAL(20, 4), doc="工程物资")
    PROV_NOM_RISKS = Column(DECIMAL(20, 4), doc="一般风险准备")
    PROVISIONS = Column(DECIMAL(20, 4), doc="预计负债")
    R_AND_D_COSTS = Column(DECIMAL(20, 4), doc="开发支出")
    RCV_CEDED_CLAIM_RSRV = Column(DECIMAL(20, 4), doc="应收分保未决赔款准备金")
    RCV_CEDED_LIFE_INSUR_RSRV = Column(DECIMAL(20, 4), doc="应收分保寿险责任准备金")
    RCV_CEDED_LT_HEALTH_INSUR_RSRV = Column(DECIMAL(20, 4), doc="应收分保长期健康险责任准备金")
    RCV_CEDED_UNEARNED_PREM_RSRV = Column(DECIMAL(20, 4), doc="应收分保未到期责任准备金")
    RCV_FROM_CEDED_INSUR_CONT_RSRV = Column(DECIMAL(20, 4), doc="应收分保合同准备金")
    RCV_FROM_REINSURER = Column(DECIMAL(20, 4), doc="应收分保账款")
    RCV_INVEST = Column(DECIMAL(20, 4), doc="应收款项类投资")
    RECEIVABLES_FINANCING = Column(DECIMAL(20, 4), doc="应收款项融资")
    RED_MONETARY_CAP_FOR_SALE = Column(DECIMAL(20, 4), doc="买入返售金融资产")
    REPORT_PERIOD = Column(String(8), doc="报告期")
    RIGHT_USE_ASSETS = Column(DECIMAL(20, 4), doc="使用权资产")
    RSRV_INSUR_CONT = Column(DECIMAL(20, 4), doc="保险合同准备金")
    S_INFO_COMPCODE = Column(String(10), doc="公司ID")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    SETTLE_RSRV = Column(DECIMAL(20, 4), doc="结算备付金")
    SPE_BAL_ASSETS_DIFF = Column(DECIMAL(20, 4), doc="资产差额(特殊报表科目)")
    SPE_BAL_LIAB_DIFF = Column(DECIMAL(20, 4), doc="负债差额(特殊报表科目)")
    SPE_BAL_LIAB_EQY_DIFF = Column(DECIMAL(20, 4), doc="负债及股东权益差额(特殊报表项目)")
    SPE_BAL_SHRHLDR_EQY_DIFF = Column(DECIMAL(20, 4), doc="股东权益差额(特殊报表科目)")
    SPE_CUR_ASSETS_DIFF = Column(DECIMAL(20, 4), doc="流动资产差额(特殊报表科目)")
    SPE_CUR_LIAB_DIFF = Column(DECIMAL(20, 4), doc="流动负债差额(特殊报表科目)")
    SPE_NON_CUR_ASSETS_DIFF = Column(DECIMAL(20, 4), doc="非流动资产差额(特殊报表科目)")
    SPE_NON_CUR_LIAB_DIFF = Column(DECIMAL(20, 4), doc="非流动负债差额(特殊报表科目)")
    SPECIAL_RSRV = Column(DECIMAL(20, 4), doc="专项储备")
    SPECIFIC_ITEM_PAYABLE = Column(DECIMAL(20, 4), doc="专项应付款")
    ST_BONDS_PAYABLE = Column(DECIMAL(20, 4), doc="应付短期债券")
    ST_BORROW = Column(DECIMAL(20, 4), doc="短期借款")
    ST_FINANCING_PAYABLE = Column(DECIMAL(20, 4), doc="应付短期融资款")
    STATEMENT_TYPE = Column(String(10), doc="报表类型")
    STM_BS_TOT = Column(DECIMAL(20, 4), doc="固定资产(合计)(元)")
    SUBR_REC = Column(DECIMAL(20, 4), doc="应收代位追偿款")
    SURPLUS_RSRV = Column(DECIMAL(20, 4), doc="盈余公积金")
    TAXES_SURCHARGES_PAYABLE = Column(DECIMAL(20, 4), doc="应交税费")
    TIME_DEPOSITS = Column(DECIMAL(20, 4), doc="定期存款")
    TOT_ASSETS = Column(DECIMAL(20, 4), doc="资产总计")
    TOT_BAL_ASSETS_DIFF = Column(DECIMAL(20, 4), doc="资产差额(合计平衡项目)")
    TOT_BAL_LIAB_DIFF = Column(DECIMAL(20, 4), doc="负债差额(合计平衡项目)")
    TOT_BAL_LIAB_EQY_DIFF = Column(DECIMAL(20, 4), doc="负债及股东权益差额(合计平衡项目)")
    TOT_BAL_SHRHLDR_EQY_DIFF = Column(DECIMAL(20, 4), doc="股东权益差额(合计平衡项目)")
    TOT_CUR_ASSETS = Column(DECIMAL(20, 4), doc="流动资产合计")
    TOT_CUR_ASSETS_DIFF = Column(DECIMAL(20, 4), doc="流动资产差额(合计平衡项目)")
    TOT_CUR_LIAB = Column(DECIMAL(20, 4), doc="流动负债合计")
    TOT_CUR_LIAB_DIFF = Column(DECIMAL(20, 4), doc="流动负债差额(合计平衡项目)")
    TOT_LIAB = Column(DECIMAL(20, 4), doc="负债合计")
    TOT_LIAB_SHRHLDR_EQY = Column(DECIMAL(20, 4), doc="负债及股东权益总计")
    TOT_NON_CUR_ASSETS = Column(DECIMAL(20, 4), doc="非流动资产合计")
    TOT_NON_CUR_ASSETS_DIFF = Column(DECIMAL(20, 4), doc="非流动资产差额(合计平衡项目)")
    TOT_NON_CUR_LIAB = Column(DECIMAL(20, 4), doc="非流动负债合计")
    TOT_NON_CUR_LIAB_DIFF = Column(DECIMAL(20, 4), doc="非流动负债差额(合计平衡项目)")
    TOT_SHR = Column(DECIMAL(20, 4), doc="期末总股本")
    TOT_SHRHLDR_EQY_EXCL_MIN_INT = Column(DECIMAL(20, 4), doc="股东权益合计(不含少数股东权益)")
    TOT_SHRHLDR_EQY_INCL_MIN_INT = Column(DECIMAL(20, 4), doc="股东权益合计(含少数股东权益)")
    TRADABLE_FIN_ASSETS = Column(DECIMAL(20, 4), doc="交易性金融资产")
    TRADABLE_FIN_LIAB = Column(DECIMAL(20, 4), doc="交易性金融负债")
    UNCONFIRMED_INVEST_LOSS = Column(DECIMAL(20, 4), doc="未确认的投资损失")
    UNDISTRIBUTED_PROFIT = Column(DECIMAL(20, 4), doc="未分配利润")
    UNEARNED_PREM_RSRV = Column(DECIMAL(20, 4), doc="未到期责任准备金")
    WIND_CODE = Column(String(40), doc="Wind代码")


class ASHARECAPITALIZATION(Base):

    __tablename__ = 'ASHARECAPITALIZATION'

    ANN_DT = Column(String(8), doc="公告日期")
    CHANGE_DT = Column(String(8), doc="变动日期")
    CHANGE_DT1 = Column(String(8), doc="变动日期1")
    CUR_SIGN = Column(DECIMAL(1, 0), doc="最新标志")
    FLOAT_A_SHR = Column(DECIMAL(20, 4), doc="流通A股(万股)")
    FLOAT_B_SHR = Column(DECIMAL(20, 4), doc="流通B股(万股)")
    FLOAT_H_SHR = Column(DECIMAL(20, 4), doc="流通H股(万股)")
    FLOAT_OVERSEAS_SHR = Column(DECIMAL(20, 4), doc="境外流通股(万股)")
    FLOAT_SHR = Column(DECIMAL(20, 4), doc="流通股(万股)")
    IS_VALID = Column(DECIMAL(5, 0), doc="是否有效")
    NON_TRADABLE_SHR = Column(DECIMAL(20, 4), doc="非流通股")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    OTHER_RESTRICTED_SHR = Column(DECIMAL(20, 4), doc="其他限售股")
    RESTRICTED_A_SHR = Column(DECIMAL(20, 4), doc="限售A股(万股)")
    RESTRICTED_B_SHR = Column(DECIMAL(20, 4), doc="限售B股(万股)")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    S_SHARE_CHANGEREASON = Column(String(30), doc="股本变动原因")
    S_SHARE_H = Column(DECIMAL(20, 4), doc="香港上市股")
    S_SHARE_NONTRADABLE = Column(DECIMAL(20, 4), doc="股改前非流通股")
    S_SHARE_NTRD_DOMESINITOR = Column(DECIMAL(20, 4), doc="非流通股(境内法人股:境内发起人股)")
    S_SHARE_NTRD_FUNDBAL = Column(DECIMAL(20, 4), doc="非流通股(境内法人股:基金持股)")
    S_SHARE_NTRD_GENJURIS = Column(DECIMAL(20, 4), doc="非流通股(境内法人股:一般法人股)")
    S_SHARE_NTRD_INSDEREMP = Column(DECIMAL(20, 4), doc="内部职工股(万股)")
    S_SHARE_NTRD_IPOINIP = Column(DECIMAL(20, 4), doc="非流通股(自然人股)")
    S_SHARE_NTRD_IPOJURIS = Column(DECIMAL(20, 4), doc="非流通股(境内法人股:募集法人股)")
    S_SHARE_NTRD_NET = Column(DECIMAL(20, 4), doc="NET股(万股)")
    S_SHARE_NTRD_NONLSTFRGN = Column(DECIMAL(20, 4), doc="非流通股(非上市外资股)")
    S_SHARE_NTRD_PRFSHARE = Column(DECIMAL(20, 4), doc="优先股(万股)")
    S_SHARE_NTRD_SNORMNGER = Column(DECIMAL(20, 4), doc="流通股(高管持股)")
    S_SHARE_NTRD_STAQ = Column(DECIMAL(20, 4), doc="STAQ股(万股)")
    S_SHARE_NTRD_STATE = Column(DECIMAL(20, 4), doc="非流通股(国家股)")
    S_SHARE_NTRD_STATE_PCT = Column(DECIMAL(20, 4), doc="非流通股(国有股)")
    S_SHARE_NTRD_STATJUR = Column(DECIMAL(20, 4), doc="非流通股(国有法人股)")
    S_SHARE_NTRD_STRTINVESTOR = Column(DECIMAL(20, 4), doc="非流通股(境内法人股:战略投资者持股)")
    S_SHARE_NTRD_SUBDOMESJUR = Column(DECIMAL(20, 4), doc="非流通股(境内法人股)")
    S_SHARE_NTRD_TRFNSHARE = Column(DECIMAL(20, 4), doc="转配股(万股)")
    S_SHARE_OTCA = Column(DECIMAL(20, 4), doc="三板A股")
    S_SHARE_OTCB = Column(DECIMAL(20, 4), doc="三板B股")
    S_SHARE_RTD_DOMESJUR = Column(DECIMAL(20, 4), doc="限售A股(其他内资持股:境内法人持股)")
    S_SHARE_RTD_DOMESNP = Column(DECIMAL(20, 4), doc="限售A股(其他内资持股:境内自然人持股)")
    S_SHARE_RTD_FRGNJUR = Column(DECIMAL(20, 4), doc="限售A股(境外法人持股)")
    S_SHARE_RTD_FRGNNP = Column(DECIMAL(20, 4), doc="限售A股(境外自然人持股)")
    S_SHARE_RTD_INST = Column(DECIMAL(20, 4), doc="限售A股(其他内资持股:机构配售股)")
    S_SHARE_RTD_SENMANAGER = Column(DECIMAL(20, 4), doc="限售股份(高管持股)(万股)")
    S_SHARE_RTD_STATE = Column(DECIMAL(20, 4), doc="限售A股(国家持股)")
    S_SHARE_RTD_STATEJUR = Column(DECIMAL(20, 4), doc="限售A股(国有法人持股)")
    S_SHARE_RTD_SUBFRGN = Column(DECIMAL(20, 4), doc="限售A股(外资持股)")
    S_SHARE_RTD_SUBOTHERDOMES = Column(DECIMAL(20, 4), doc="限售A股(其他内资持股)")
    S_SHARE_TOTALA = Column(DECIMAL(20, 4), doc="A股合计")
    S_SHARE_TOTALB = Column(DECIMAL(20, 4), doc="B股合计")
    S_SHARE_TOTALOTC = Column(DECIMAL(20, 4), doc="三板合计")
    S_SHARE_TOTALRESTRICTED = Column(DECIMAL(20, 4), doc="限售股合计")
    S_SHARE_TOTALTRADABLE = Column(DECIMAL(20, 4), doc="流通股合计")
    TOT_SHR = Column(DECIMAL(20, 4), doc="总股本(万股)")
    WIND_CODE = Column(String(40), doc="Wind代码")


class ASHARECASHFLOW(Base):

    __tablename__ = 'ASHARECASHFLOW'

    ACTUAL_ANN_DT = Column(String(8), doc="实际公告日期")
    AMORT_INTANG_ASSETS = Column(DECIMAL(20, 4), doc="无形资产摊销")
    AMORT_LT_DEFERRED_EXP = Column(DECIMAL(20, 4), doc="长期待摊费用摊销")
    ANN_DT = Column(String(8), doc="公告日期")
    CASH_CASH_EQU_BEG_PERIOD = Column(DECIMAL(20, 4), doc="期初现金及现金等价物余额")
    CASH_CASH_EQU_END_PERIOD = Column(DECIMAL(20, 4), doc="期末现金及现金等价物余额")
    CASH_PAID_INVEST = Column(DECIMAL(20, 4), doc="投资支付的现金")
    CASH_PAY_ACQ_CONST_FIOLTA = Column(DECIMAL(20, 4), doc="购建固定资产、无形资产和其他长期资产支付的现金")
    CASH_PAY_BEH_EMPL = Column(DECIMAL(20, 4), doc="支付给职工以及为职工支付的现金")
    CASH_PAY_CLAIMS_ORIG_INCO = Column(DECIMAL(20, 4), doc="支付原保险合同赔付款项的现金")
    CASH_PAY_DIST_DPCP_INT_EXP = Column(DECIMAL(20, 4), doc="分配股利、利润或偿付利息支付的现金")
    CASH_PAY_GOODS_PURCH_SERV_REC = Column(DECIMAL(20, 4), doc="购买商品、接受劳务支付的现金")
    CASH_PREPAY_AMT_BORR = Column(DECIMAL(20, 4), doc="偿还债务支付的现金")
    CASH_RECP_BORROW = Column(DECIMAL(20, 4), doc="取得借款收到的现金")
    CASH_RECP_CAP_CONTRIB = Column(DECIMAL(20, 4), doc="吸收投资收到的现金")
    CASH_RECP_DISP_WITHDRWL_INVEST = Column(DECIMAL(20, 4), doc="收回投资收到的现金")
    CASH_RECP_PREM_ORIG_INCO = Column(DECIMAL(20, 4), doc="收到原保险合同保费取得的现金")
    CASH_RECP_RETURN_INVEST = Column(DECIMAL(20, 4), doc="取得投资收益收到的现金")
    CASH_RECP_SG_AND_RS = Column(DECIMAL(20, 4), doc="销售商品、提供劳务收到的现金")
    COMM_INSUR_PLCY_PAID = Column(DECIMAL(20, 4), doc="支付保单红利的现金")
    COMP_TYPE_CODE = Column(String(2), doc="公司类型代码")
    CONV_CORP_BONDS_DUE_WITHIN_1Y = Column(DECIMAL(20, 4), doc="一年内到期的可转换公司债券")
    CONV_DEBT_INTO_CAP = Column(DECIMAL(20, 4), doc="债务转为资本")
    CREDIT_IMPAIRMENT_LOSS = Column(DECIMAL(20, 4), doc="信用减值损失")
    CRNCY_CODE = Column(String(10), doc="货币代码")
    DECR_DEFERRED_EXP = Column(DECIMAL(20, 4), doc="待摊费用减少")
    DECR_DEFERRED_INC_TAX_ASSETS = Column(DECIMAL(20, 4), doc="递延所得税资产减少")
    DECR_INVENTORIES = Column(DECIMAL(20, 4), doc="存货的减少")
    DECR_OPER_PAYABLE = Column(DECIMAL(20, 4), doc="经营性应收项目的减少")
    DEPR_FA_COGA_DPBA = Column(DECIMAL(20, 4), doc="固定资产折旧、油气资产折耗、生产性生物资产折旧")
    EFF_FX_FLU_CASH = Column(DECIMAL(20, 4), doc="汇率变动对现金的影响")
    END_BAL_CASH = Column(DECIMAL(20, 4), doc="现金的期末余额")
    FA_FNC_LEASES = Column(DECIMAL(20, 4), doc="融资租入固定资产")
    FIN_EXP = Column(DECIMAL(20, 4), doc="财务费用")
    FREE_CASH_FLOW = Column(DECIMAL(20, 4), doc="企业自由现金流量(FCFF)")
    HANDLING_CHRG_PAID = Column(DECIMAL(20, 4), doc="支付手续费的现金")
    IM_NET_CASH_FLOWS_OPER_ACT = Column(DECIMAL(20, 4), doc="间接法-经营活动产生的现金流量净额")
    IM_NET_INCR_CASH_CASH_EQU = Column(DECIMAL(20, 4), doc="间接法-现金及现金等价物净增加额")
    INCL_CASH_REC_SAIMS = Column(DECIMAL(20, 4), doc="其中:子公司吸收少数股东投资收到的现金")
    INCL_DVD_PROFIT_PAID_SC_MS = Column(DECIMAL(20, 4), doc="其中:子公司支付给少数股东的股利、利润")
    INCR_ACC_EXP = Column(DECIMAL(20, 4), doc="预提费用增加")
    INCR_DEFERRED_INC_TAX_LIAB = Column(DECIMAL(20, 4), doc="递延所得税负债增加")
    INCR_OPER_PAYABLE = Column(DECIMAL(20, 4), doc="经营性应付项目的增加")
    INVEST_LOSS = Column(DECIMAL(20, 4), doc="投资损失")
    IS_CALCULATION = Column(DECIMAL(5, 0), doc="是否计算报表")
    LESS_BEG_BAL_CASH = Column(DECIMAL(20, 4), doc="减:现金的期初余额")
    LESS_BEG_BAL_CASH_EQU = Column(DECIMAL(20, 4), doc="减:现金等价物的期初余额")
    LOSS_DISP_FIOLTA = Column(DECIMAL(20, 4), doc="处置固定、无形资产和其他长期资产的损失")
    LOSS_FV_CHG = Column(DECIMAL(20, 4), doc="公允价值变动损失")
    LOSS_SCR_FA = Column(DECIMAL(20, 4), doc="固定资产报废损失")
    NET_CASH_FLOWS_FNC_ACT = Column(DECIMAL(20, 4), doc="筹资活动产生的现金流量净额")
    NET_CASH_FLOWS_INV_ACT = Column(DECIMAL(20, 4), doc="投资活动产生的现金流量净额")
    NET_CASH_FLOWS_OPER_ACT = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额")
    NET_CASH_PAY_AQUIS_SOBU = Column(DECIMAL(20, 4), doc="取得子公司及其他营业单位支付的现金净额")
    NET_CASH_RECEIVED_REINSU_BUS = Column(DECIMAL(20, 4), doc="收到再保业务现金净额")
    NET_CASH_RECP_DISP_FIOLTA = Column(DECIMAL(20, 4), doc="处置固定资产、无形资产和其他长期资产收回的现金净额")
    NET_CASH_RECP_DISP_SOBU = Column(DECIMAL(20, 4), doc="处置子公司及其他营业单位收到的现金净额")
    NET_INCR_CASH_CASH_EQU = Column(DECIMAL(20, 4), doc="现金及现金等价物净增加额")
    NET_INCR_CLIENTS_LOAN_ADV = Column(DECIMAL(20, 4), doc="客户贷款及垫款净增加额")
    NET_INCR_DEP_CBOB = Column(DECIMAL(20, 4), doc="存放央行和同业款项净增加额")
    NET_INCR_DEP_COB = Column(DECIMAL(20, 4), doc="客户存款和同业存放款项净增加额")
    NET_INCR_DISP_FAAS = Column(DECIMAL(20, 4), doc="处置可供出售金融资产净增加额")
    NET_INCR_DISP_TFA = Column(DECIMAL(20, 4), doc="处置交易性金融资产净增加额")
    NET_INCR_FUND_BORR_OFI = Column(DECIMAL(20, 4), doc="向其他金融机构拆入资金净增加额")
    NET_INCR_INSURED_DEP = Column(DECIMAL(20, 4), doc="保户储金净增加额")
    NET_INCR_INT_HANDLING_CHRG = Column(DECIMAL(20, 4), doc="收取利息和手续费净增加额")
    NET_INCR_LOANS_CENTRAL_BANK = Column(DECIMAL(20, 4), doc="向中央银行借款净增加额")
    NET_INCR_LOANS_OTHER_BANK = Column(DECIMAL(20, 4), doc="拆入资金净增加额")
    NET_INCR_PLEDGE_LOAN = Column(DECIMAL(20, 4), doc="质押贷款净增加额")
    NET_INCR_REPURCH_BUS_FUND = Column(DECIMAL(20, 4), doc="回购业务资金净增加额")
    NET_PROFIT = Column(DECIMAL(20, 4), doc="净利润")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    OTHER_CASH_PAY_RAL_FNC_ACT = Column(DECIMAL(20, 4), doc="支付其他与筹资活动有关的现金")
    OTHER_CASH_PAY_RAL_INV_ACT = Column(DECIMAL(20, 4), doc="支付其他与投资活动有关的现金")
    OTHER_CASH_PAY_RAL_OPER_ACT = Column(DECIMAL(20, 4), doc="支付其他与经营活动有关的现金")
    OTHER_CASH_RECP_RAL_FNC_ACT = Column(DECIMAL(20, 4), doc="收到其他与筹资活动有关的现金")
    OTHER_CASH_RECP_RAL_INV_ACT = Column(DECIMAL(20, 4), doc="收到其他与投资活动有关的现金")
    OTHER_CASH_RECP_RAL_OPER_ACT = Column(DECIMAL(20, 4), doc="收到其他与经营活动有关的现金")
    OTHER_IMPAIR_LOSS_ASSETS = Column(DECIMAL(20, 4), doc="其他资产减值损失")
    OTHERS = Column(DECIMAL(20, 4), doc="其他")
    PAY_ALL_TYP_TAX = Column(DECIMAL(20, 4), doc="支付的各项税费")
    PLUS_END_BAL_CASH_EQU = Column(DECIMAL(20, 4), doc="加:现金等价物的期末余额")
    PLUS_PROV_DEPR_ASSETS = Column(DECIMAL(20, 4), doc="加:资产减值准备")
    PROC_ISSUE_BONDS = Column(DECIMAL(20, 4), doc="发行债券收到的现金")
    RECP_TAX_RENDS = Column(DECIMAL(20, 4), doc="收到的税费返还")
    REPORT_PERIOD = Column(String(8), doc="报告期")
    RIGHT_USE_ASSETS_DEP = Column(DECIMAL(20, 4), doc="使用权资产折旧")
    S_DISMANTLE_CAPITAL_ADD_NET = Column(DECIMAL(20, 4), doc="拆出资金净增加额")
    S_INFO_COMPCODE = Column(String(10), doc="公司ID")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    SECURITIE_NETCASH_RECEIVED = Column(DECIMAL(20, 4), doc="代理买卖证券收到的现金净额(元)")
    SPE_BAL_CASH_INFLOWS_FNC = Column(DECIMAL(20, 4), doc="筹资活动现金流入差额(特殊报表科目)")
    SPE_BAL_CASH_INFLOWS_INV = Column(DECIMAL(20, 4), doc="投资活动现金流入差额(特殊报表科目)")
    SPE_BAL_CASH_INFLOWS_OPER = Column(DECIMAL(20, 4), doc="经营活动现金流入差额(特殊报表科目)")
    SPE_BAL_CASH_OUTFLOWS_FNC = Column(DECIMAL(20, 4), doc="筹资活动现金流出差额(特殊报表科目)")
    SPE_BAL_CASH_OUTFLOWS_INV = Column(DECIMAL(20, 4), doc="投资活动现金流出差额(特殊报表科目)")
    SPE_BAL_CASH_OUTFLOWS_OPER = Column(DECIMAL(20, 4), doc="经营活动现金流出差额(特殊报表科目)")
    SPE_BAL_NETCASH_EQU_UNDIR = Column(DECIMAL(20, 4), doc="间接法-经营活动现金流量净额差额(特殊报表科目)")
    SPE_BAL_NETCASH_INC = Column(DECIMAL(20, 4), doc="现金净增加额差额(特殊报表科目)")
    SPE_BAL_NETCASH_INC_UNDIR = Column(DECIMAL(20, 4), doc="间接法-现金净增加额差额(特殊报表科目)")
    STATEMENT_TYPE = Column(String(10), doc="报表类型")
    STOT_CASH_INFLOWS_FNC_ACT = Column(DECIMAL(20, 4), doc="筹资活动现金流入小计")
    STOT_CASH_INFLOWS_INV_ACT = Column(DECIMAL(20, 4), doc="投资活动现金流入小计")
    STOT_CASH_INFLOWS_OPER_ACT = Column(DECIMAL(20, 4), doc="经营活动现金流入小计")
    STOT_CASH_OUTFLOWS_FNC_ACT = Column(DECIMAL(20, 4), doc="筹资活动现金流出小计")
    STOT_CASH_OUTFLOWS_INV_ACT = Column(DECIMAL(20, 4), doc="投资活动现金流出小计")
    STOT_CASH_OUTFLOWS_OPER_ACT = Column(DECIMAL(20, 4), doc="经营活动现金流出小计")
    TOT_BAL_CASH_INFLOWS_FNC = Column(DECIMAL(20, 4), doc="筹资活动现金流入差额(合计平衡项目)")
    TOT_BAL_CASH_INFLOWS_INV = Column(DECIMAL(20, 4), doc="投资活动现金流入差额(合计平衡项目)")
    TOT_BAL_CASH_INFLOWS_OPER = Column(DECIMAL(20, 4), doc="经营活动现金流入差额(合计平衡项目)")
    TOT_BAL_CASH_OUTFLOWS_FNC = Column(DECIMAL(20, 4), doc="筹资活动现金流出差额(合计平衡项目)")
    TOT_BAL_CASH_OUTFLOWS_INV = Column(DECIMAL(20, 4), doc="投资活动现金流出差额(合计平衡项目)")
    TOT_BAL_CASH_OUTFLOWS_OPER = Column(DECIMAL(20, 4), doc="经营活动现金流出差额(合计平衡项目)")
    TOT_BAL_NETCASH_EQU_UNDIR = Column(DECIMAL(20, 4), doc="间接法-经营活动现金流量净额差额(合计平衡项目)")
    TOT_BAL_NETCASH_INC = Column(DECIMAL(20, 4), doc="现金净增加额差额(合计平衡项目)")
    TOT_BAL_NETCASH_INC_UNDIR = Column(DECIMAL(20, 4), doc="间接法-现金净增加额差额(合计平衡项目)")
    TOT_BAL_NETCASH_OUTFLOWS_FNC = Column(DECIMAL(20, 4), doc="筹资活动产生的现金流量净额差额(合计平衡项目)")
    TOT_BAL_NETCASH_OUTFLOWS_INV = Column(DECIMAL(20, 4), doc="投资活动产生的现金流量净额差额(合计平衡项目)")
    TOT_BAL_NETCASH_OUTFLOWS_OPER = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额差额(合计平衡项目)")
    UNCONFIRMED_INVEST_LOSS = Column(DECIMAL(20, 4), doc="未确认投资损失")
    WIND_CODE = Column(String(40), doc="Wind代码")


class ASHAREDESCRIPTION(Base):

    __tablename__ = 'ASHAREDESCRIPTION'

    CRNCY_CODE = Column(String(10), doc="货币代码")
    IS_SHSC = Column(DECIMAL(5, 0), doc="是否在沪股通或深港通范围内")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_INFO_CODE = Column(String(40), doc="交易代码")
    S_INFO_COMPCODE = Column(String(100), doc="公司ID")
    S_INFO_COMPNAME = Column(String(100), doc="公司中文名称")
    S_INFO_COMPNAMEENG = Column(String(100), doc="公司英文名称")
    S_INFO_DELISTDATE = Column(String(8), doc="退市日期")
    S_INFO_EXCHMARKET = Column(String(40), doc="交易所")
    S_INFO_ISINCODE = Column(String(40), doc="ISIN代码")
    S_INFO_LISTBOARD = Column(String(10), doc="上市板类型")
    S_INFO_LISTBOARDNAME = Column(String(10), doc="上市板")
    S_INFO_LISTDATE = Column(String(8), doc="上市日期")
    S_INFO_NAME = Column(String(50), doc="证券简称")
    S_INFO_PINYIN = Column(String(40), doc="简称拼音")
    S_INFO_SEDOLCODE = Column(String(40))
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")


class ASHAREDIVIDEND(Base):

    __tablename__ = 'ASHAREDIVIDEND'

    ANN_DT = Column(String(8), doc="最新公告日期")
    CASH_DVD_PER_SH_AFTER_TAX = Column(DECIMAL(24, 8), doc="每股派息(税后)(元)")
    CASH_DVD_PER_SH_PRE_TAX = Column(DECIMAL(24, 8), doc="每股派息(税前)(元)")
    CRNCY_CODE = Column(String(10), doc="货币代码")
    DVD_ANN_DT = Column(String(8), doc="分红实施公告日")
    DVD_PAYOUT_DT = Column(String(8), doc="派息日")
    EQY_RECORD_DT = Column(String(8), doc="股权登记日")
    EX_DT = Column(String(8), doc="除权除息日")
    IS_CHANGED = Column(DECIMAL(5, 0), doc="方案是否变更")
    IS_TRANSFER = Column(DECIMAL(1, 0), doc="是否不分转")
    LISTING_DT_OF_DVD_SHR = Column(String(8), doc="红股上市日")
    MEMO = Column(String(200), doc="备注")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    REPORT_PERIOD = Column(String(8), doc="分红年度")
    S_DIV_BASEDATE = Column(String(8), doc="基准日期")
    S_DIV_BASESHARE = Column(DECIMAL(20, 4), doc="基准股本(万股)")
    S_DIV_BONUSRATE = Column(DECIMAL(20, 8), doc="每股送股比例")
    S_DIV_CHANGE = Column(String(500), doc="方案变更说明")
    S_DIV_CONVERSEDRATE = Column(DECIMAL(20, 8), doc="每股转增比例")
    S_DIV_OBJECT = Column(String(100), doc="分红对象")
    S_DIV_PREANNDT = Column(String(8), doc="预案预披露公告日")
    S_DIV_PRELANDATE = Column(String(8), doc="预案公告日")
    S_DIV_PROGRESS = Column(String(10), doc="方案进度")
    S_DIV_SMTGDATE = Column(String(8), doc="股东大会公告日")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    STK_DVD_PER_SH = Column(DECIMAL(20, 8), doc="每股送转")
    WIND_CODE = Column(String(40), doc="Wind代码")


class ASHAREFINANCIALINDICATOR(Base):

    __tablename__ = 'ASHAREFINANCIALINDICATOR'

    ANN_DT = Column(String(8), doc="公告日期")
    CRNCY_CODE = Column(String(10), doc="货币代码")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    RD_EXPENSE = Column(DECIMAL(20, 4), doc="研发费用")
    REPORT_PERIOD = Column(String(8), doc="报告期")
    S_FA_ADMINEXPENSETOGR = Column(DECIMAL(20, 4), doc="管理费用/营业总收入")
    S_FA_ARTURN = Column(DECIMAL(20, 4), doc="应收账款周转率")
    S_FA_ARTURNDAYS = Column(DECIMAL(20, 4), doc="应收账款周转天数")
    S_FA_ASSETSTOEQUITY = Column(DECIMAL(20, 4), doc="权益乘数")
    S_FA_ASSETSTURN = Column(DECIMAL(20, 4), doc="总资产周转率")
    S_FA_BPS = Column(DECIMAL(20, 4), doc="每股净资产")
    S_FA_CAPITALIZEDTODA = Column(DECIMAL(20, 4), doc="资本支出/折旧和摊销")
    S_FA_CASHRATIO = Column(DECIMAL(20, 4), doc="保守速动比率")
    S_FA_CASHTOLIQDEBT = Column(DECIMAL(20, 4), doc="货币资金／流动负债")
    S_FA_CASHTOLIQDEBTWITHINTEREST = Column(DECIMAL(20, 4), doc="货币资金／带息流动负债")
    S_FA_CATOASSETS = Column(DECIMAL(20, 4), doc="流动资产/总资产")
    S_FA_CATURN = Column(DECIMAL(20, 4), doc="流动资产周转率")
    S_FA_CFPS = Column(DECIMAL(20, 4), doc="每股现金流量净额")
    S_FA_COGSTOSALES = Column(DECIMAL(20, 4), doc="销售成本率")
    S_FA_CURRENT = Column(DECIMAL(20, 4), doc="流动比率")
    S_FA_CURRENTDEBTTODEBT = Column(DECIMAL(20, 4), doc="流动负债/负债合计")
    S_FA_DEBTTOASSETS = Column(DECIMAL(20, 4), doc="资产负债率")
    S_FA_DEBTTOEQUITY = Column(DECIMAL(20, 4), doc="产权比率")
    S_FA_DEDUCTEDPROFIT = Column(DECIMAL(20, 4), doc="扣除非经常性损益后的净利润(扣除少数股东损益)")
    S_FA_DEDUCTEDPROFITTOPROFIT = Column(DECIMAL(20, 4), doc="扣除非经常损益后的净利润/净利润")
    S_FA_DUPONT_ASSETSTOEQUITY = Column(DECIMAL(20, 4), doc="权益乘数(用于杜邦分析)")
    S_FA_DUPONT_ROA = Column(DECIMAL(20, 4), doc="总资产净利率(杜邦分析)")
    S_FA_EBIT = Column(DECIMAL(20, 4), doc="息税前利润")
    S_FA_EBITDA = Column(DECIMAL(20, 4), doc="息税折旧摊销前利润")
    S_FA_EBITDATODEBT = Column(DECIMAL(20, 4), doc="息税折旧摊销前利润/负债合计")
    S_FA_EBITPS = Column(DECIMAL(20, 4), doc="每股息税前利润")
    S_FA_EBITTOGR = Column(DECIMAL(20, 4), doc="息税前利润/营业总收入")
    S_FA_EBITTOINTEREST = Column(DECIMAL(20, 4), doc="已获利息倍数(EBIT/利息费用)")
    S_FA_EPS_BASIC = Column(DECIMAL(20, 4), doc="基本每股收益")
    S_FA_EPS_DILUTED = Column(DECIMAL(20, 4), doc="稀释每股收益")
    S_FA_EPS_DILUTED2 = Column(DECIMAL(20, 4), doc="期末摊薄每股收益")
    S_FA_EQUITYTODEBT = Column(DECIMAL(20, 4), doc="归属于母公司的股东权益/负债合计")
    S_FA_EQUITYTOINTERESTDEBT = Column(DECIMAL(20, 4), doc="归属于母公司的股东权益/带息债务")
    S_FA_EQUITYTOTOTALCAPITAL = Column(DECIMAL(20, 4), doc="归属于母公司的股东权益/全部投入资本")
    S_FA_EXINTERESTDEBT_CURRENT = Column(DECIMAL(20, 4), doc="无息流动负债")
    S_FA_EXINTERESTDEBT_NONCURRENT = Column(DECIMAL(20, 4), doc="无息非流动负债")
    S_FA_EXPENSETOSALES = Column(DECIMAL(20, 4), doc="销售期间费用率")
    S_FA_EXTRAORDINARY = Column(DECIMAL(20, 4), doc="非经常性损益")
    S_FA_FATURN = Column(DECIMAL(20, 4), doc="固定资产周转率")
    S_FA_FCFE = Column(DECIMAL(20, 4), doc="股权自由现金流量(FCFE)")
    S_FA_FCFEPS = Column(DECIMAL(20, 4), doc="每股股东自由现金流量")
    S_FA_FCFF = Column(DECIMAL(20, 4), doc="企业自由现金流量(FCFF)")
    S_FA_FCFFPS = Column(DECIMAL(20, 4), doc="每股企业自由现金流量")
    S_FA_FINAEXPENSETOGR = Column(DECIMAL(20, 4), doc="财务费用/营业总收入")
    S_FA_GCTOGR = Column(DECIMAL(20, 4), doc="营业总成本/营业总收入")
    S_FA_GROSSMARGIN = Column(DECIMAL(20, 4), doc="毛利")
    S_FA_GROSSPROFITMARGIN = Column(DECIMAL(20, 4), doc="销售毛利率")
    S_FA_GRPS = Column(DECIMAL(20, 4), doc="每股营业总收入")
    S_FA_IMPAIRTOGR_TTM = Column(DECIMAL(20, 4), doc="资产减值损失/营业总收入")
    S_FA_INTDEBTTOTOTALCAP = Column(DECIMAL(20, 4), doc="带息债务/全部投入资本")
    S_FA_INTERESTDEBT = Column(DECIMAL(20, 4), doc="带息债务")
    S_FA_INVESTCAPITAL = Column(DECIMAL(20, 4), doc="全部投入资本")
    S_FA_INVESTINCOME = Column(DECIMAL(20, 4), doc="价值变动净收益")
    S_FA_INVESTINCOMETOEBT = Column(DECIMAL(20, 4), doc="价值变动净收益/利润总额")
    S_FA_INVTURN = Column(DECIMAL(20, 4), doc="存货周转率")
    S_FA_INVTURNDAYS = Column(DECIMAL(20, 4), doc="存货周转天数")
    S_FA_LONGDEBTODEBT = Column(DECIMAL(20, 4), doc="非流动负债/负债合计")
    S_FA_LONGDEBTTOWORKINGCAPITAL = Column(DECIMAL(20, 4), doc="长期债务与营运资金比率")
    S_FA_NCATOASSETS = Column(DECIMAL(20, 4), doc="非流动资产/总资产")
    S_FA_NETDEBT = Column(DECIMAL(20, 4), doc="净债务")
    S_FA_NETPROFITMARGIN = Column(DECIMAL(20, 4), doc="销售净利率")
    S_FA_NETWORKINGCAPITAL = Column(DECIMAL(20, 4), doc="营运流动资本")
    S_FA_NONOPERATEPROFITTOEBT = Column(DECIMAL(20, 4), doc="营业外收支净额/利润总额")
    S_FA_NONOPPROFIT = Column(DECIMAL(20, 4), doc="非营业利润")
    S_FA_NOPTOEBT = Column(DECIMAL(20, 4), doc="非营业利润／利润总额")
    S_FA_OCFPS = Column(DECIMAL(20, 4), doc="每股经营活动产生的现金流量净额")
    S_FA_OCFTODEBT = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额/负债合计")
    S_FA_OCFTOINTERESTDEBT = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额/带息债务")
    S_FA_OCFTONETDEBT = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额/净债务")
    S_FA_OCFTOOPERATEINCOME = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额/经营活动净收益")
    S_FA_OCFTOOR = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额/营业收入")
    S_FA_OCFTOPROFIT = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额／营业利润")
    S_FA_OCFTOSHORTDEBT = Column(DECIMAL(20, 4), doc="经营活动产生的现金流量净额/流动负债")
    S_FA_OPERATEINCOME = Column(DECIMAL(20, 4), doc="经营活动净收益")
    S_FA_OPERATEINCOMETOEBT = Column(DECIMAL(20, 4), doc="经营活动净收益/利润总额")
    S_FA_OPTODEBT = Column(DECIMAL(20, 4), doc="营业利润／负债合计")
    S_FA_OPTOEBT = Column(DECIMAL(20, 4), doc="营业利润／利润总额")
    S_FA_OPTOGR = Column(DECIMAL(20, 4), doc="营业利润/营业总收入")
    S_FA_OPTOLIQDEBT = Column(DECIMAL(20, 4), doc="营业利润／流动负债")
    S_FA_ORPS = Column(DECIMAL(20, 4), doc="每股营业收入")
    S_FA_PREFINEXPENSE_OPPROFIT = Column(DECIMAL(20, 4), doc="扣除财务费用前营业利润")
    S_FA_PROFITTOGR = Column(DECIMAL(20, 4), doc="净利润/营业总收入")
    S_FA_PROFITTOOP = Column(DECIMAL(20, 4), doc="利润总额／营业收入")
    S_FA_QUICK = Column(DECIMAL(20, 4), doc="速动比率")
    S_FA_RETAINEDEARNINGS = Column(DECIMAL(20, 4), doc="留存收益")
    S_FA_RETAINEDPS = Column(DECIMAL(20, 4), doc="每股留存收益")
    S_FA_ROA = Column(DECIMAL(20, 4), doc="总资产净利率")
    S_FA_ROA2 = Column(DECIMAL(20, 4), doc="总资产报酬率")
    S_FA_ROA2_YEARLY = Column(DECIMAL(20, 4), doc="年化总资产报酬率")
    S_FA_ROA_YEARLY = Column(DECIMAL(20, 4), doc="年化总资产净利率")
    S_FA_ROE = Column(DECIMAL(20, 4), doc="净资产收益率")
    S_FA_ROE_AVG = Column(DECIMAL(20, 4), doc="平均净资产收益率(增发条件)")
    S_FA_ROE_DEDUCTED = Column(DECIMAL(20, 4), doc="净资产收益率(扣除非经常损益)")
    S_FA_ROE_YEARLY = Column(DECIMAL(20, 4), doc="年化净资产收益率")
    S_FA_ROIC = Column(DECIMAL(20, 4), doc="投入资本回报率")
    S_FA_ROIC_YEARLY = Column(DECIMAL(20, 4), doc="年化投入资本回报率")
    S_FA_SALEEXPENSETOGR = Column(DECIMAL(20, 4), doc="销售费用/营业总收入")
    S_FA_SALESCASHINTOOR = Column(DECIMAL(20, 4), doc="销售商品提供劳务收到的现金/营业收入")
    S_FA_SURPLUSCAPITALPS = Column(DECIMAL(20, 4), doc="每股资本公积")
    S_FA_SURPLUSRESERVEPS = Column(DECIMAL(20, 4), doc="每股盈余公积")
    S_FA_TANGASSETTOINTDEBT = Column(DECIMAL(20, 4), doc="有形资产/带息债务")
    S_FA_TANGIBLEASSET = Column(DECIMAL(20, 4), doc="有形资产")
    S_FA_TANGIBLEASSETSTOASSETS = Column(DECIMAL(20, 4), doc="有形资产/总资产")
    S_FA_TANGIBLEASSETTODEBT = Column(DECIMAL(20, 4), doc="有形资产/负债合计")
    S_FA_TANGIBLEASSETTONETDEBT = Column(DECIMAL(20, 4), doc="有形资产/净债务")
    S_FA_TAXTOEBT = Column(DECIMAL(20, 4), doc="所得税/利润总额")
    S_FA_TOT_FATURN = Column(DECIMAL(20, 4), doc="固定资产合计周转率")
    S_FA_TURNDAYS = Column(DECIMAL(20, 4), doc="营业周期")
    S_FA_UNDISTRIBUTEDPS = Column(DECIMAL(20, 4), doc="每股未分配利润")
    S_FA_WORKINGCAPITAL = Column(DECIMAL(20, 4), doc="营运资金")
    S_FA_YOY_EQUITY = Column(DECIMAL(20, 4), doc="净资产(同比增长率)")
    S_FA_YOY_OR = Column(DECIMAL(20, 4), doc="营业收入同比增长率(%)")
    S_FA_YOY_TR = Column(DECIMAL(20, 4), doc="营业总收入同比增长率(%)")
    S_FA_YOYASSETS = Column(DECIMAL(20, 4), doc="相对年初增长率-资产总计(%)")
    S_FA_YOYBPS = Column(DECIMAL(20, 4), doc="相对年初增长率-每股净资产(%)")
    S_FA_YOYEBT = Column(DECIMAL(20, 4), doc="同比增长率-利润总额(%)")
    S_FA_YOYEPS_BASIC = Column(DECIMAL(20, 4), doc="同比增长率-基本每股收益(%)")
    S_FA_YOYEPS_DILUTED = Column(DECIMAL(20, 4), doc="同比增长率-稀释每股收益(%)")
    S_FA_YOYEQUITY = Column(DECIMAL(20, 4), doc="相对年初增长率-归属母公司的股东权益(%)")
    S_FA_YOYNETPROFIT = Column(DECIMAL(20, 4), doc="同比增长率-归属母公司股东的净利润(%)")
    S_FA_YOYNETPROFIT_DEDUCTED = Column(DECIMAL(20, 4), doc="同比增长率-归属母公司股东的净利润-扣除非经常损益(%)")
    S_FA_YOYOCF = Column(DECIMAL(20, 4), doc="同比增长率-经营活动产生的现金流量净额(%)")
    S_FA_YOYOCFPS = Column(DECIMAL(20, 4), doc="同比增长率-每股经营活动产生的现金流量净额(%)")
    S_FA_YOYOP = Column(DECIMAL(20, 4), doc="同比增长率-营业利润(%)")
    S_FA_YOYROE = Column(DECIMAL(20, 4), doc="同比增长率-净资产收益率(摊薄)(%)")
    S_INFO_COMPCODE = Column(String(10), doc="公司ID")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    S_QFA_ADMINEXPENSETOGR = Column(DECIMAL(20, 4), doc="单季度.管理费用／营业总收入")
    S_QFA_CGRGR = Column(DECIMAL(20, 4), doc="单季度.营业总收入环比增长率(%)")
    S_QFA_CGRNETPROFIT = Column(DECIMAL(20, 4), doc="单季度.归属母公司股东的净利润环比增长率(%)")
    S_QFA_CGROP = Column(DECIMAL(20, 4), doc="单季度.营业利润环比增长率(%)")
    S_QFA_CGRPROFIT = Column(DECIMAL(20, 4), doc="单季度.净利润环比增长率(%)")
    S_QFA_CGRSALES = Column(DECIMAL(20, 4), doc="单季度.营业收入环比增长率(%)")
    S_QFA_DEDUCTEDPROFIT = Column(DECIMAL(20, 4), doc="单季度.扣除非经常损益后的净利润")
    S_QFA_DEDUCTEDPROFITTOPROFIT = Column(DECIMAL(20, 4), doc="单季度.扣除非经常损益后的净利润／净利润")
    S_QFA_EPS = Column(DECIMAL(24, 6), doc="单季度.每股收益")
    S_QFA_EXPENSETOSALES = Column(DECIMAL(20, 4), doc="单季度.销售期间费用率")
    S_QFA_FINAEXPENSETOGR = Column(DECIMAL(20, 4), doc="单季度.财务费用／营业总收入")
    S_QFA_GCTOGR = Column(DECIMAL(20, 4), doc="单季度.营业总成本／营业总收入")
    S_QFA_GROSSPROFITMARGIN = Column(DECIMAL(20, 4), doc="单季度.销售毛利率")
    S_QFA_IMPAIRTOGR_TTM = Column(DECIMAL(20, 4), doc="单季度.资产减值损失／营业总收入")
    S_QFA_INVESTINCOME = Column(DECIMAL(20, 4), doc="单季度.价值变动净收益")
    S_QFA_INVESTINCOMETOEBT = Column(DECIMAL(20, 4), doc="单季度.价值变动净收益／利润总额")
    S_QFA_NETPROFITMARGIN = Column(DECIMAL(20, 4), doc="单季度.销售净利率")
    S_QFA_OCFTOOR = Column(DECIMAL(20, 4), doc="单季度.经营活动产生的现金流量净额／经营活动净收益")
    S_QFA_OCFTOSALES = Column(DECIMAL(20, 4), doc="单季度.经营活动产生的现金流量净额／营业收入")
    S_QFA_OPERATEINCOME = Column(DECIMAL(20, 4), doc="单季度.经营活动净收益")
    S_QFA_OPERATEINCOMETOEBT = Column(DECIMAL(20, 4), doc="单季度.经营活动净收益／利润总额")
    S_QFA_OPTOGR = Column(DECIMAL(20, 4), doc="单季度.营业利润／营业总收入")
    S_QFA_PROFITTOGR = Column(DECIMAL(20, 4), doc="单季度.净利润／营业总收入")
    S_QFA_ROA = Column(DECIMAL(20, 4), doc="单季度.总资产净利润")
    S_QFA_ROE = Column(DECIMAL(24, 6), doc="单季度.净资产收益率")
    S_QFA_ROE_DEDUCTED = Column(DECIMAL(24, 6), doc="单季度.净资产收益率(扣除非经常损益)")
    S_QFA_SALEEXPENSETOGR = Column(DECIMAL(20, 4), doc="单季度.销售费用／营业总收入")
    S_QFA_SALESCASHINTOOR = Column(DECIMAL(20, 4), doc="单季度.销售商品提供劳务收到的现金／营业收入")
    S_QFA_YOYGR = Column(DECIMAL(20, 4), doc="单季度.营业总收入同比增长率(%)")
    S_QFA_YOYNETPROFIT = Column(DECIMAL(20, 4), doc="单季度.归属母公司股东的净利润同比增长率(%)")
    S_QFA_YOYOP = Column(DECIMAL(20, 4), doc="单季度.营业利润同比增长率(%)")
    S_QFA_YOYPROFIT = Column(DECIMAL(20, 4), doc="单季度.净利润同比增长率(%)")
    S_QFA_YOYSALES = Column(DECIMAL(20, 4), doc="单季度.营业收入同比增长率(%)")
    S_STM_BS = Column(DECIMAL(20, 4), doc="固定资产合计")
    S_STM_IS = Column(DECIMAL(20, 4), doc="折旧与摊销")
    S_STMNOTE_FINEXP = Column(DECIMAL(20, 4), doc="利息费用")
    WAA_ROE = Column(DECIMAL(24, 6), doc="加权平均净资产收益率")
    WIND_CODE = Column(String(40), doc="Wind代码")


class ASHAREFREEFLOAT(Base):

    __tablename__ = 'ASHAREFREEFLOAT'

    ANN_DT = Column(String(8), doc="公告日期")
    CHANGE_DT = Column(String(8), doc="变动日期(除权日)")
    CHANGE_DT1 = Column(String(8), doc="变动日期(上市日)")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    S_SHARE_FREESHARES = Column(DECIMAL(20, 4), doc="自由流通股本(万股)")


class ASHAREINCOME(Base):

    __tablename__ = 'ASHAREINCOME'

    ACTUAL_ANN_DT = Column(String(8), doc="实际公告日期")
    ADJLOSSGAIN_PREVYEAR = Column(DECIMAL(20, 4), doc="调整以前年度损益")
    ANN_DT = Column(String(8), doc="公告日期")
    ASSET_DISPOSAL_INCOME = Column(DECIMAL(20, 4), doc="资产处置收益")
    CAPITALIZED_COMSTOCK_DIV = Column(DECIMAL(20, 4), doc="转作股本的普通股股利")
    CHG_INSUR_CONT_RSRV = Column(DECIMAL(20, 4), doc="提取保险责任准备金")
    CHG_UNEARNED_PREM_RES = Column(DECIMAL(20, 4), doc="提取未到期责任准备金")
    COMP_TYPE_CODE = Column(String(2), doc="公司类型代码")
    COMSHARE_DVD_PAYABLE = Column(DECIMAL(20, 4), doc="应付普通股股利")
    CONTINUED_NET_PROFIT = Column(DECIMAL(20, 4), doc="持续经营净利润")
    CREDIT_IMPAIRMENT_LOSS = Column(DECIMAL(20, 4), doc="信用减值损失")
    CRNCY_CODE = Column(String(10), doc="货币代码")
    DISTRIBUTABLE_PROFIT = Column(DECIMAL(20, 4), doc="可分配利润")
    DISTRIBUTABLE_PROFIT_SHRHDER = Column(DECIMAL(20, 4), doc="可供股东分配的利润")
    DVD_EXP_INSURED = Column(DECIMAL(20, 4), doc="保户红利支出")
    EBIT = Column(DECIMAL(20, 4), doc="息税前利润")
    EBITDA = Column(DECIMAL(20, 4), doc="息税折旧摊销前利润")
    END_NET_PROFIT = Column(DECIMAL(20, 4), doc="终止经营净利润")
    FIN_EXP_INT_INC = Column(DECIMAL(20, 4), doc="财务费用:利息收入")
    HANDLING_CHRG_COMM_INC = Column(DECIMAL(20, 4), doc="手续费及佣金收入")
    IL_NET_LOSS_DISP_NONCUR_ASSET = Column(DECIMAL(20, 4), doc="其中:减:非流动资产处置净损失")
    INC_TAX = Column(DECIMAL(20, 4), doc="所得税")
    INCL_INC_INVEST_ASSOC_JV_ENTP = Column(DECIMAL(20, 4), doc="其中:对联营企业和合营企业的投资收益")
    INCL_REINSURANCE_PREM_INC = Column(DECIMAL(20, 4), doc="其中:分保费收入")
    INSUR_PREM_UNEARNED = Column(DECIMAL(20, 4), doc="已赚保费")
    INSURANCE_EXPENSE = Column(DECIMAL(20, 4), doc="保险业务支出")
    INT_INC = Column(DECIMAL(20, 4), doc="利息收入")
    IS_CALCULATION = Column(DECIMAL(5, 0), doc="是否计算报表")
    LESS_CEDED_OUT_PREM = Column(DECIMAL(20, 4), doc="减:分出保费")
    LESS_CLAIM_RECB_REINSURER = Column(DECIMAL(20, 4), doc="减:摊回赔付支出")
    LESS_EXP_RECB_REINSURER = Column(DECIMAL(20, 4), doc="减:摊回分保费用")
    LESS_FIN_EXP = Column(DECIMAL(20, 4), doc="减:财务费用")
    LESS_GERL_ADMIN_EXP = Column(DECIMAL(20, 4), doc="减:管理费用")
    LESS_HANDLING_CHRG_COMM_EXP = Column(DECIMAL(20, 4), doc="减:手续费及佣金支出")
    LESS_IMPAIR_LOSS_ASSETS = Column(DECIMAL(20, 4), doc="减:资产减值损失")
    LESS_INS_RSRV_RECB_REINSURER = Column(DECIMAL(20, 4), doc="减:摊回保险责任准备金")
    LESS_INT_EXP = Column(DECIMAL(20, 4), doc="减:利息支出")
    LESS_NON_OPER_EXP = Column(DECIMAL(20, 4), doc="减:营业外支出")
    LESS_OPER_COST = Column(DECIMAL(20, 4), doc="减:营业成本")
    LESS_SELLING_DIST_EXP = Column(DECIMAL(20, 4), doc="减:销售费用")
    LESS_TAXES_SURCHARGES_OPS = Column(DECIMAL(20, 4), doc="减:营业税金及附加")
    MEMO = Column(String(1000), doc="备注")
    MINORITY_INT_INC = Column(DECIMAL(20, 4), doc="少数股东损益")
    NET_AFTER_DED_NR_LP_CORRECT = Column(DECIMAL(20, 4), doc="扣除非经常性损益后的净利润(财务重要指标(更正前))")
    NET_EXPOSURE_HEDGING_BENEFITS = Column(DECIMAL(20, 4), doc="净敞口套期收益")
    NET_HANDLING_CHRG_COMM_INC = Column(DECIMAL(20, 4), doc="手续费及佣金净收入")
    NET_INC_EC_ASSET_MGMT_BUS = Column(DECIMAL(20, 4), doc="受托客户资产管理业务净收入")
    NET_INC_OTHER_OPS = Column(DECIMAL(20, 4), doc="其他经营净收益")
    NET_INC_SEC_TRADING_BROK_BUS = Column(DECIMAL(20, 4), doc="代理买卖证券业务净收入")
    NET_INC_SEC_UW_BUS = Column(DECIMAL(20, 4), doc="证券承销业务净收入")
    NET_INT_INC = Column(DECIMAL(20, 4), doc="利息净收入")
    NET_PROFIT_AFTER_DED_NR_LP = Column(DECIMAL(20, 4), doc="扣除非经常性损益后净利润（扣除少数股东损益）")
    NET_PROFIT_EXCL_MIN_INT_INC = Column(DECIMAL(20, 4), doc="净利润(不含少数股东损益)")
    NET_PROFIT_INCL_MIN_INT_INC = Column(DECIMAL(20, 4), doc="净利润(含少数股东损益)")
    NET_PROFIT_UNDER_INTL_ACC_STA = Column(DECIMAL(20, 4), doc="国际会计准则净利润")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPER_EXP = Column(DECIMAL(20, 4), doc="营业支出")
    OPER_PROFIT = Column(DECIMAL(20, 4), doc="营业利润")
    OPER_REV = Column(DECIMAL(20, 4), doc="营业收入")
    OPMODE = Column(String(1))
    OTHER_BUS_COST = Column(DECIMAL(20, 4), doc="其他业务成本")
    OTHER_BUS_INC = Column(DECIMAL(20, 4), doc="其他业务收入")
    OTHER_COMPREH_INC = Column(DECIMAL(20, 4), doc="其他综合收益")
    OTHER_IMPAIR_LOSS_ASSETS = Column(DECIMAL(20, 4), doc="其他资产减值损失")
    OTHER_INCOME = Column(DECIMAL(20, 4), doc="其他收益")
    PLUS_NET_GAIN_CHG_FV = Column(DECIMAL(20, 4), doc="加:公允价值变动净收益")
    PLUS_NET_GAIN_FX_TRANS = Column(DECIMAL(20, 4), doc="加:汇兑净收益")
    PLUS_NET_INC_OTHER_BUS = Column(DECIMAL(20, 4), doc="加:其他业务净收益")
    PLUS_NET_INVEST_INC = Column(DECIMAL(20, 4), doc="加:投资净收益")
    PLUS_NON_OPER_REV = Column(DECIMAL(20, 4), doc="加:营业外收入")
    PREM_INC = Column(DECIMAL(20, 4), doc="保费业务收入")
    PREPAY_SURR = Column(DECIMAL(20, 4), doc="退保金")
    PRFSHARE_DVD_PAYABLE = Column(DECIMAL(20, 4), doc="应付优先股股利")
    RD_EXPENSE = Column(DECIMAL(20, 4), doc="研发费用")
    REINSURANCE_EXP = Column(DECIMAL(20, 4), doc="分保费用")
    REPORT_PERIOD = Column(String(8), doc="报告期")
    S_FA_EPS_BASIC = Column(DECIMAL(20, 4), doc="基本每股收益")
    S_FA_EPS_DILUTED = Column(DECIMAL(20, 4), doc="稀释每股收益")
    S_INFO_COMPCODE = Column(String(10), doc="公司ID")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    SPE_BAL_NET_PROFIT = Column(DECIMAL(20, 4), doc="净利润差额(特殊报表科目)")
    SPE_BAL_OPER_PROFIT = Column(DECIMAL(20, 4), doc="营业利润差额(特殊报表科目)")
    SPE_BAL_TOT_PROFIT = Column(DECIMAL(20, 4), doc="利润总额差额(特殊报表科目)")
    STATEMENT_TYPE = Column(String(10), doc="报表类型")
    STMNOTE_FINEXP = Column(DECIMAL(20, 4), doc="财务费用:利息费用")
    TOT_BAL_NET_PROFIT = Column(DECIMAL(20, 4), doc="净利润差额(合计平衡项目)")
    TOT_BAL_OPER_PROFIT = Column(DECIMAL(20, 4), doc="营业利润差额(合计平衡项目)")
    TOT_BAL_TOT_PROFIT = Column(DECIMAL(20, 4), doc="利润总额差额(合计平衡项目)")
    TOT_CLAIM_EXP = Column(DECIMAL(20, 4), doc="赔付总支出")
    TOT_COMPREH_INC = Column(DECIMAL(20, 4), doc="综合收益总额")
    TOT_COMPREH_INC_MIN_SHRHLDR = Column(DECIMAL(20, 4), doc="综合收益总额(少数股东)")
    TOT_COMPREH_INC_PARENT_COMP = Column(DECIMAL(20, 4), doc="综合收益总额(母公司)")
    TOT_OPER_COST = Column(DECIMAL(20, 4), doc="营业总成本")
    TOT_OPER_COST2 = Column(DECIMAL(20, 4), doc="营业总成本2")
    TOT_OPER_REV = Column(DECIMAL(20, 4), doc="营业总收入")
    TOT_PROFIT = Column(DECIMAL(20, 4), doc="利润总额")
    TRANSFER_FROM_HOUSINGIMPREST = Column(DECIMAL(20, 4), doc="住房周转金转入")
    TRANSFER_FROM_OTHERS = Column(DECIMAL(20, 4), doc="其他转入")
    TRANSFER_FROM_SURPLUSRESERVE = Column(DECIMAL(20, 4), doc="盈余公积转入")
    UNCONFIRMED_INVEST_LOSS = Column(DECIMAL(20, 4), doc="未确认投资损失")
    UNDISTRIBUTED_PROFIT = Column(DECIMAL(20, 4), doc="年初未分配利润")
    WIND_CODE = Column(String(40), doc="Wind代码")
    WITHDR_BUZEXPWELFARE = Column(DECIMAL(20, 4), doc="提取企业发展基金")
    WITHDR_LEGALPUBWELFUNDS = Column(DECIMAL(20, 4), doc="提取法定公益金")
    WITHDR_LEGALSURPLUS = Column(DECIMAL(20, 4), doc="提取法定盈余公积")
    WITHDR_OTHERSURPRESERVE = Column(DECIMAL(20, 4), doc="提取任意盈余公积金")
    WITHDR_RESERVEFUND = Column(DECIMAL(20, 4), doc="提取储备基金")
    WORKERS_WELFARE = Column(DECIMAL(20, 4), doc="职工奖金福利")


class ASHAREINDUSTRIESCODE(Base):

    __tablename__ = 'ASHAREINDUSTRIESCODE'

    CHINESEDEFINITION = Column(String(600), doc="板块中文定义")
    INDUSTRIESALIAS = Column(String(12), doc="板块别名")
    INDUSTRIESCODE = Column(String(38), doc="行业代码")
    INDUSTRIESCODE_OLD = Column(String(38), doc="行业代码(旧)")
    INDUSTRIESNAME = Column(String(50), doc="行业名称")
    LEVELNUM = Column(DECIMAL(1, 0), doc="级数")
    MEMO = Column(String(100), doc="备注")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    SEQUENCE = Column(DECIMAL(4, 0), doc="展示序号")
    USED = Column(DECIMAL(1, 0), doc="是否有效")
    WIND_NAME_ENG = Column(String(200), doc="板块英文名称")


class ASHAREPROFITEXPRESS(Base):

    __tablename__ = 'ASHAREPROFITEXPRESS'

    ACTUAL_ANN_DT = Column(String(8), doc="[内部]实际公告日期")
    ANN_DT = Column(String(8), doc="公告日期")
    BRIEF_PERFORMANCE = Column(String(2000), doc="业绩简要说明")
    EPS_DILUTED = Column(DECIMAL(20, 4), doc="每股收益-基本(元)")
    GROWTH_BPS_SH = Column(DECIMAL(20, 4), doc="比年初增长率:归属于母公司股东的每股净资产")
    LAST_YEAR_EPS_DILUTED = Column(DECIMAL(20, 4), doc="去年同期每股收益")
    LAST_YEAR_NET_PROFIT_EXCL_INC = Column(DECIMAL(20, 4), doc="去年同期净利润")
    LAST_YEAR_OPER_PROFIT = Column(DECIMAL(20, 4), doc="去年同期营业利润")
    LAST_YEAR_OPER_REV = Column(DECIMAL(20, 4), doc="去年同期营业收入")
    LAST_YEAR_TOT_PROFIT = Column(DECIMAL(20, 4), doc="去年同期利润总额")
    MEMO = Column(String(400), doc="备注")
    NET_PROFIT_EXCL_MIN_INT_INC = Column(DECIMAL(20, 4), doc="净利润(元)")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPER_PROFIT = Column(DECIMAL(20, 4), doc="营业利润(元)")
    OPER_REV = Column(DECIMAL(20, 4), doc="营业收入(元)")
    OPMODE = Column(String(1))
    REPORT_PERIOD = Column(String(8), doc="报告期")
    ROE_DILUTED = Column(DECIMAL(20, 4), doc="净资产收益率-加权(%)")
    S_EARLY_BPS = Column(DECIMAL(20, 4), doc="期初每股净资产")
    S_EARLY_NET_ASSETS = Column(DECIMAL(20, 4), doc="期初净资产")
    S_FA_BPS = Column(DECIMAL(20, 4), doc="每股净资产")
    S_FA_GROWTH_ASSETS = Column(DECIMAL(20, 4), doc="比年初增长率:总资产")
    S_FA_ROE_YEARLY = Column(DECIMAL(20, 4), doc="同比增减:加权平均净资产收益率")
    S_FA_YOYEBT = Column(DECIMAL(20, 4), doc="同比增长率:利润总额")
    S_FA_YOYEPS_BASIC = Column(DECIMAL(20, 4), doc="同比增长率:基本每股收益")
    S_FA_YOYEQUITY = Column(DECIMAL(20, 4), doc="比年初增长率:归属母公司的股东权益")
    S_FA_YOYNETPROFIT_DEDUCTED = Column(DECIMAL(20, 4), doc="同比增长率:归属母公司股东的净利润")
    S_FA_YOYOP = Column(DECIMAL(20, 4), doc="同比增长率:营业利润")
    S_FA_YOYSALES = Column(DECIMAL(20, 4), doc="同比增长率:营业收入")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    S_ISAUDIT = Column(DECIMAL(5, 0), doc="是否审计")
    TOT_ASSETS = Column(DECIMAL(20, 4), doc="总资产(元)")
    TOT_PROFIT = Column(DECIMAL(20, 4), doc="利润总额(元)")
    TOT_SHRHLDR_EQY_EXCL_MIN_INT = Column(DECIMAL(20, 4), doc="股东权益合计(不含少数股东权益)(元)")
    YOYNET_PROFIT_EXCL_MIN_INT_INC = Column(DECIMAL(20, 4), doc="去年同期修正后净利润")


class ASHARERIGHTISSUE(Base):

    __tablename__ = 'ASHARERIGHTISSUE'

    ANN_DT = Column(String(8), doc="最新公告日期")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_ALLOTMENT_OBJECT = Column(String(40), doc="配股对象")
    S_CIRCULATED_SHARE_NUM = Column(DECIMAL(20, 4), doc="已流通股理论配股数量(万股)")
    S_CIRCULATED_SHARE_NUM1 = Column(DECIMAL(20, 4), doc="已流通股实际配股数量(万股)")
    S_EMPLOYEE_STOCK_SHARE_NUM = Column(DECIMAL(20, 4), doc="职工股理论配股数量(万股)")
    S_EMPLOYEE_STOCK_SHARE_NUM1 = Column(DECIMAL(20, 4), doc="职工股实际配股数量(万股)")
    S_EXPECTED_FUND_RAISING = Column(DECIMAL(20, 4), doc="预计募集资金(元)")
    S_HOLDER_HELD_NUMBER = Column(DECIMAL(20, 4), doc="持股5%以上大股东持股数量(万股)")
    S_HOLDER_SUBSCRIPTION_METHOD = Column(String(100), doc="持股5%以上大股东认购方式(万股)")
    S_HOLDER_SUBSCRIPTION_NUMBER = Column(DECIMAL(20, 4), doc="持股5%以上大股东认购股数量(万股)")
    S_HOLDER_SUBSCRIPTION_NUMBER1 = Column(DECIMAL(20, 4), doc="持股5%以上的大股东理论认购股数量(万股)")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    S_LEGAL_PERSON_SHARE_NUM = Column(DECIMAL(20, 4), doc="法人股理论配股数量(万股)")
    S_LEGAL_PERSON_SHARE_NUM1 = Column(DECIMAL(20, 4), doc="法人股实际配股数量(万股)")
    S_LOWER_PRICE_LIMIT = Column(DECIMAL(20, 4), doc="配股预案价下限")
    S_PRICE_CAP = Column(DECIMAL(20, 4), doc="配股预案价上限")
    S_RATIO_DENOMINATOR = Column(DECIMAL(20, 4), doc="配股比例分母")
    S_RATIO_MOLECULAR = Column(DECIMAL(20, 4), doc="配股比例分子")
    S_RIGHTSISSUE_AMOUNT = Column(DECIMAL(20, 4), doc="配股计划数量(万股)")
    S_RIGHTSISSUE_AMOUNTACT = Column(DECIMAL(20, 4), doc="配股实际数量(万股)")
    S_RIGHTSISSUE_ANNCEDATE = Column(String(8), doc="配股实施公告日")
    S_RIGHTSISSUE_APPROVEDDATE = Column(String(8), doc="证监会核准公告日")
    S_RIGHTSISSUE_CODE = Column(String(10), doc="配售代码")
    S_RIGHTSISSUE_CONTENT = Column(String(150), doc="配股说明")
    S_RIGHTSISSUE_COST = Column(DECIMAL(20, 4), doc="配售费用")
    S_RIGHTSISSUE_EXDIVIDENDDATE = Column(String(8), doc="除权日")
    S_RIGHTSISSUE_GUARANTOR = Column(String(8), doc="基准年度")
    S_RIGHTSISSUE_GUARTYPE = Column(DECIMAL(20, 4), doc="基准股本(万股)")
    S_RIGHTSISSUE_LISTANNDATE = Column(String(8), doc="上市公告日")
    S_RIGHTSISSUE_LISTEDDATE = Column(String(8), doc="配股上市日")
    S_RIGHTSISSUE_NAME = Column(String(40), doc="配股简称")
    S_RIGHTSISSUE_NETCOLLECTION = Column(DECIMAL(20, 4), doc="募集资金(元)")
    S_RIGHTSISSUE_PASSDATE = Column(String(8), doc="发审委通过公告日")
    S_RIGHTSISSUE_PAYENDDATE = Column(String(8), doc="缴款终止日")
    S_RIGHTSISSUE_PAYSTARTDATE = Column(String(8), doc="缴款起始日")
    S_RIGHTSISSUE_PREPLANDATE = Column(String(8), doc="预案公告日")
    S_RIGHTSISSUE_PRICE = Column(DECIMAL(20, 4), doc="配股价格(元)")
    S_RIGHTSISSUE_PROGRESS = Column(String(10), doc="方案进度")
    S_RIGHTSISSUE_RATIO = Column(DECIMAL(20, 4), doc="配股比例")
    S_RIGHTSISSUE_REGDATE_BSHARE = Column(String(8), doc="B股股权登记日")
    S_RIGHTSISSUE_REGDATESHAREB = Column(String(8), doc="股权登记日")
    S_RIGHTSISSUE_RESULTDATE = Column(String(8), doc="配股结果公告日")
    S_RIGHTSISSUE_SMTGANNCEDATE = Column(String(8), doc="股东大会公告日")
    S_RIGHTSISSUE_YEAR = Column(String(8), doc="配股年度")
    S_STATE_OWNED_SHARE_NUM = Column(DECIMAL(20, 4), doc="国有股理论配股数量(万股)")
    S_STATE_OWNED_SHARE_NUM1 = Column(DECIMAL(20, 4), doc="国有股实际配股数量(万股)")
    S_SUBSCRIPTION_METHOD = Column(String(30), doc="认购方式")
    S_TRANSFER_SHARE_NUM = Column(DECIMAL(20, 4), doc="转配股理论配股数量(万股)")
    S_TRANSFER_SHARE_NUM1 = Column(DECIMAL(20, 4), doc="转配股实际配股数量(万股)")
    S_UNDERWRITER_SUBSCRIPTION = Column(DECIMAL(20, 4), doc="承销商余额认购数量(万股)")
    S_UNDERWRITING_METHOD = Column(String(20), doc="承销方式")


class CFUNDWINDINDEXCOMPONENT(Base):

    __tablename__ = 'CFUNDWINDINDEXCOMPONENT'

    OBJECT_ID = Column(String(38), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_CON_CODE = Column(String(16), doc="成份板块代码")
    S_CON_NAME = Column(String(100), doc="成份板块名称")
    S_INFO_WINDCODE = Column(String(40), doc="指数Wind代码")


class CHINAMUTUALFUNDASSETPORTFOLIO(Base):

    __tablename__ = 'CHINAMUTUALFUNDASSETPORTFOLIO'

    CRNCY_CODE = Column(String(10), doc="货币代码")
    F_ANN_DATE = Column(String(8), doc="公告日期")
    F_MMF_AVGPTM = Column(DECIMAL(20, 4), doc="投资组合平均剩余期限(天)")
    F_MMF_REPO = Column(DECIMAL(20, 4), doc="卖出回购证券(元)")
    F_MMF_REVERSEREPO = Column(DECIMAL(20, 4), doc="买入返售证券(元)")
    F_PRT_ABSVALUE = Column(DECIMAL(20, 4), doc="持有资产支持证券市值(元)")
    F_PRT_ABSVALUETONAV = Column(DECIMAL(20, 4), doc="持有资产支持证券占资产净值比例(%)")
    F_PRT_BDTONAV_NOGOV = Column(DECIMAL(20, 4), doc="持有债券市值(不含国债)占资产净值比例(%)")
    F_PRT_BDVALUE_NOGOV = Column(DECIMAL(20, 4), doc="持有债券市值(不含国债)(元)")
    F_PRT_BONDTONAV = Column(DECIMAL(20, 4), doc="持有债券市值总计占资产净值比例(%)")
    F_PRT_BONDTONAVCHANGE = Column(DECIMAL(20, 4), doc="持有债券比例较上期变化(%)")
    F_PRT_BONDTOTOT = Column(DECIMAL(20, 4), doc="持有债券市值占资产总值比例(%)")
    F_PRT_BONDVALUE = Column(DECIMAL(20, 4), doc="持有债券市值总计(元)")
    F_PRT_CASH = Column(DECIMAL(20, 4), doc="持有现金(元)")
    F_PRT_CASHTONAV = Column(DECIMAL(20, 4), doc="持有现金占资产净值比例(%)")
    F_PRT_CASHTONAVCHANGE = Column(DECIMAL(20, 4), doc="持有现金比例较上期变化(%)")
    F_PRT_CASHTOTOT = Column(DECIMAL(20, 4), doc="持有现金占资产总值比例(%)")
    F_PRT_CDS = Column(DECIMAL(20, 4), doc="持有同业存单市值(元)")
    F_PRT_CORPBOND = Column(DECIMAL(20, 4), doc="持有企债市值(元)")
    F_PRT_CORPBONDTONAV = Column(DECIMAL(20, 4), doc="持有企债市值占资产净值比例(%)")
    F_PRT_COVERTBOND = Column(DECIMAL(15, 2), doc="持有可转债市值(元)")
    F_PRT_COVERTBONDTONAV = Column(DECIMAL(20, 4), doc="持有可转债市值占资产净值比例(%)")
    F_PRT_CPVALUE = Column(DECIMAL(20, 4), doc="持有短期融资券市值(元)")
    F_PRT_CTRBANKBILL = Column(DECIMAL(20, 4), doc="持有央行票据市值(元)")
    F_PRT_CTRBANKBILLTONAV = Column(DECIMAL(20, 4), doc="持有央行票据市值占资产净值比例(%)")
    F_PRT_DEBCREBALANCE = Column(DECIMAL(20, 4), doc="借贷方差额(元)")
    F_PRT_ENDDATE = Column(String(8), doc="截止日期")
    F_PRT_FINANBOND = Column(DECIMAL(20, 4), doc="持有金融债市值(元)")
    F_PRT_FINANBONDTONAV = Column(DECIMAL(20, 4), doc="持有金融债市值占资产净值比例(%)")
    F_PRT_FUNDTONAV = Column(DECIMAL(20, 4), doc="持有基金市值占资产净值比例(%)")
    F_PRT_FUNDTOTOT = Column(DECIMAL(20, 4), doc="持有基金市值占资产总值比例(%)")
    F_PRT_FUNDVALUE = Column(DECIMAL(20, 4), doc="持有基金市值(元)")
    F_PRT_GOVBOND = Column(DECIMAL(20, 4), doc="持有国债市值(元)")
    F_PRT_GOVBONDTONAV = Column(DECIMAL(20, 4), doc="持有国债市值占资产净值比例(%)")
    F_PRT_GOVCASHTONAV = Column(DECIMAL(20, 4), doc="持有国债及现金占资产净值比例(%)")
    F_PRT_GOVCASHVALUE = Column(DECIMAL(20, 4), doc="持有国债及现金总值(元)")
    F_PRT_HKSTOCKTONAV = Column(DECIMAL(20, 4), doc="港股通投资港股市值占资产净值比")
    F_PRT_HKSTOCKVALUE = Column(DECIMAL(20, 4), doc="港股通投资港股市值")
    F_PRT_MMTONAV = Column(DECIMAL(20, 4), doc="持有货币市场工具市值占资产净值比例(%)")
    F_PRT_MMTOTOT = Column(DECIMAL(20, 4), doc="持有货币市场工具市值占资产总值比例(%)")
    F_PRT_MMVALUE = Column(DECIMAL(20, 4), doc="持有货币市场工具市值(元)")
    F_PRT_MTNVALUE = Column(DECIMAL(20, 4), doc="持有中期票据市值(元)")
    F_PRT_NETASSET = Column(DECIMAL(20, 4), doc="资产净值(元)")
    F_PRT_OTHER = Column(DECIMAL(20, 4), doc="持有其他资产(元)")
    F_PRT_OTHERTONAV = Column(DECIMAL(20, 4), doc="持有其他资产占资产净值比例(%)")
    F_PRT_OTHERTOTOT = Column(DECIMAL(20, 4), doc="持有其他资产占资产总值比例(%)")
    F_PRT_OTHERTOTOTCHANGE = Column(DECIMAL(20, 4), doc="持有其他资产比例较上期变化(%)")
    F_PRT_PASVSTKTONAV = Column(DECIMAL(20, 4), doc="指数投资持有股票市值占资产净值比例(%)")
    F_PRT_PASVSTKVALUE = Column(DECIMAL(15, 2), doc="指数投资持有股票市值(元)")
    F_PRT_POLIFINANBDTONAV = Column(DECIMAL(20, 4), doc="持有政策性金融债市值占资产净值比例(%)")
    F_PRT_POLIFINANBDVALUE = Column(DECIMAL(20, 4), doc="持有政策性金融债市值(元)")
    F_PRT_POSVSTKTONAV = Column(DECIMAL(20, 4), doc="积极投资持有股票市值占资产净值比例(%)")
    F_PRT_POSVSTKVALUE = Column(DECIMAL(20, 4), doc="积极投资持有股票市值(元)")
    F_PRT_REVERSEREPOTONAV = Column(DECIMAL(20, 4), doc="持有买入返售证券占资产净值比例(%)")
    F_PRT_REVERSEREPOTOTOT = Column(DECIMAL(20, 4), doc="持有买入返售证券占资产总值比例(%)")
    F_PRT_STOCKTONAV = Column(DECIMAL(20, 4), doc="持有股票市值占资产净值比例(%)")
    F_PRT_STOCKTONAVCHANGE = Column(DECIMAL(20, 4), doc="持有股票比例较上期变化(%)")
    F_PRT_STOCKTOTOT = Column(DECIMAL(20, 4), doc="持有股票市值占资产总值比例(%)")
    F_PRT_STOCKVALUE = Column(DECIMAL(20, 4), doc="持有股票市值(元)")
    F_PRT_TOTALASSET = Column(DECIMAL(20, 4), doc="资产总值(元)")
    F_PRT_WARRANTONAV = Column(DECIMAL(20, 4), doc="持有权证市值占资产净值比例(%)")
    F_PRT_WARRANTOTOT = Column(DECIMAL(20, 4), doc="持有权证市值占资产总值比例(%)")
    F_PRT_WARRANTVALUE = Column(DECIMAL(20, 4), doc="持有权证市值(元)")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")


class CHINAMUTUALFUNDNAV(Base):

    __tablename__ = 'CHINAMUTUALFUNDNAV'

    ANN_DATE = Column(String(8), doc="公告日期")
    CRNCY_CODE = Column(String(10), doc="货币代码")
    F_ASSET_MERGEDSHARESORNOT = Column(DECIMAL(1, 0), doc="是否合计数据")
    F_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    F_NAV_ACCUMULATED = Column(DECIMAL(24, 8), doc="累计净值")
    F_NAV_ADJFACTOR = Column(DECIMAL(24, 8), doc="复权因子")
    F_NAV_ADJUSTED = Column(DECIMAL(22, 8), doc="复权单位净值")
    F_NAV_DISTRIBUTION = Column(DECIMAL(20, 4), doc="累计单位分配")
    F_NAV_DIVACCUMULATED = Column(DECIMAL(20, 4), doc="累计分红(废弃)")
    F_NAV_UNIT = Column(DECIMAL(24, 8), doc="单位净值")
    F_PRT_NETASSET = Column(DECIMAL(20, 4), doc="资产净值")
    IS_EXDIVIDENDDATE = Column(DECIMAL(5, 0), doc="是否净值除权日")
    NETASSET_TOTAL = Column(DECIMAL(20, 4), doc="合计资产净值")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    PRICE_DATE = Column(String(8), doc="截止日期")


class CHINAMUTUALFUNDREPNAVPER(Base):

    __tablename__ = 'CHINAMUTUALFUNDREPNAVPER'

    ANN_DATE = Column(String(8), doc="公告日期")
    F_INFO_REPORTPERIOD = Column(String(8), doc="报告期")
    F_NAV_BENCHDEVRETURN = Column(DECIMAL(20, 4), doc="净值增长率减基准收益率")
    F_NAV_BENCHRETURN = Column(DECIMAL(20, 4), doc="业绩比较基准收益率")
    F_NAV_BENCHSTDDEV = Column(DECIMAL(20, 4), doc="业绩比较基准收益率标准差")
    F_NAV_RETURN = Column(DECIMAL(20, 4), doc="净值增长率")
    F_NAV_STDDEVNAVBENCH = Column(DECIMAL(20, 4), doc="净值增长率标准差减基准收益率标准差")
    F_NAV_STDDEVRETURN = Column(DECIMAL(20, 4), doc="净值增长率标准差")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    PERIOD_CODE = Column(String(10), doc="期间代码")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")


class CHINAMUTUALFUNDSEATTRADING(Base):

    __tablename__ = 'CHINAMUTUALFUNDSEATTRADING'

    CRNCY_CODE = Column(String(10), doc="货币代码")
    F_COMMISSIONAM = Column(DECIMAL(20, 4), doc="交易佣金(元)")
    F_COMMISSIONPRO = Column(DECIMAL(20, 4), doc="交易佣金占比(%)")
    F_TRADE_BONDAM = Column(DECIMAL(20, 4), doc="债券交易金额(元)")
    F_TRADE_BONDPRO = Column(DECIMAL(20, 4), doc="债券交易金额占比(%)")
    F_TRADE_FUNDAM = Column(DECIMAL(20, 4), doc="基金交易金额(元)")
    F_TRADE_FUNDPRO = Column(DECIMAL(20, 4), doc="基金交易金额占比(%)")
    F_TRADE_REPOAM = Column(DECIMAL(20, 4), doc="回购交易金额(元)")
    F_TRADE_REPOPRO = Column(DECIMAL(20, 4), doc="回购交易金额占比(%)")
    F_TRADE_SBAM = Column(DECIMAL(20, 4), doc="股票债券成交金额(元)")
    F_TRADE_SBPRO = Column(DECIMAL(20, 4), doc="股票债券交易量占比(%)")
    F_TRADE_STOCKAM = Column(DECIMAL(20, 4), doc="股票交易金额(元)")
    F_TRADE_STOCKPRO = Column(DECIMAL(20, 4), doc="股票交易金额占比(%)")
    F_TRADE_WARRANTAM = Column(DECIMAL(20, 4), doc="权证交易金额(元)")
    F_TRADE_WARRANTPRO = Column(DECIMAL(20, 4), doc="权证交易金额占比(%)")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_INFO_REPORTPERIOD = Column(String(8), doc="报告期")
    S_INFO_SECURNAME = Column(String(100), doc="证券公司简称")
    S_INFO_WINDCODE = Column(String(40), doc="Wind代码")


class CMFINDUSTRYPLATE(Base):

    __tablename__ = 'CMFINDUSTRYPLATE'

    OBJECT_ID = Column(String(38), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_INFO_NAME = Column(String(100), doc="板块名称")
    S_INFO_SECTOR = Column(String(16), doc="板块代码")
    S_INFO_WINDCODE = Column(String(40), doc="成份万得代码")


class CMFIOPVNAV(Base):

    __tablename__ = 'CMFIOPVNAV'

    F_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    F_IOPV_NAV = Column(DECIMAL(20, 8), doc="IOPV收盘净值")
    OBJECT_ID = Column(String(38), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    PRICE_DATE = Column(String(8), doc="日期")


class CMFNAVOPERATIONRECORD(Base):

    __tablename__ = 'CMFNAVOPERATIONRECORD'

    F_INFO_WINDCODE = Column(String(40), doc="Wind代码")
    F_NAV_OLD = Column(DECIMAL(11, 6), doc="调整前净值")
    FUND_NAV_OBJECT_ID = Column(String(38), doc="基金净值表记录ID")
    HANDLE_ACTION = Column(String(20), doc="处理动作")
    HANDLE_DATE = Column(String(8), doc="处理日期")
    OBJECT_ID = Column(String(38), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    PRICE_DATE = Column(String(8), doc="净值截止日期")


class CMFTHEMECONCEPT(Base):

    __tablename__ = 'CMFTHEMECONCEPT'

    OBJECT_ID = Column(String(38), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_INFO_NAME = Column(String(100), doc="板块名称")
    S_INFO_SECTOR = Column(String(16), doc="板块代码")
    S_INFO_WINDCODE = Column(String(40), doc="成份万得代码")


class COMPINTRODUCTION(Base):

    __tablename__ = 'COMPINTRODUCTION'

    ADDRESS = Column(String(200), doc="注册地址")
    BRIEFING = Column(String(2000), doc="公司简介")
    BUSINESSSCOPE = Column(LONGTEXT, doc="经营范围")
    CHAIRMAN = Column(String(100), doc="法人代表")
    CITY = Column(String(50), doc="城市")
    COMP_ID = Column(String(40), doc="公司ID")
    COMP_NAME = Column(String(200), doc="公司名称")
    COMP_NAME_ENG = Column(String(100), doc="英文名称")
    COMP_PROPERTY = Column(String(100), doc="企业性质")
    COMP_SNAME = Column(String(40), doc="公司中文简称")
    COMP_SNAMEENG = Column(String(100), doc="英文名称缩写")
    COMP_TYPE = Column(String(100), doc="公司类型")
    COMPANY_TYPE = Column(String(10), doc="公司类别")
    COUNTRY = Column(String(20), doc="国籍")
    CURRENCYCODE = Column(String(10), doc="货币代码")
    DISCLOSER = Column(String(500), doc="信息披露人")
    EMAIL = Column(String(200), doc="电子邮件")
    ENDDATE = Column(String(8), doc="公司终止日期")
    FAX = Column(String(50), doc="传真")
    FOUNDDATE = Column(String(8), doc="成立日期")
    IS_LISTED = Column(DECIMAL(1, 0), doc="是否上市公司")
    MAIN_BUSINESS = Column(String(1000), doc="主要产品及业务")
    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OFFICE = Column(String(400), doc="办公地址")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    PHONE = Column(String(50), doc="电话")
    PRESIDENT = Column(String(100), doc="总经理")
    PROVINCE = Column(String(20), doc="省份")
    REGCAPITAL = Column(DECIMAL(20, 4), doc="注册资本")
    REGISTERNUMBER = Column(String(20), doc="统一社会信用代码")
    S_INFO_COMPTYPE = Column(String(10), doc="公司类型")
    S_INFO_ORG_CODE = Column(String(30), doc="组织机构代码")
    S_INFO_TOTALEMPLOYEES = Column(DECIMAL(20, 0), doc="员工总数(人)")
    SOCIAL_CREDIT_CODE = Column(String(30), doc="统一社会信用编码(废弃)")
    WEBSITE = Column(String(200), doc="公司网址")
    ZIPCODE = Column(String(10), doc="邮编")


class INDEXCONTRASTSECTOR(Base):

    __tablename__ = 'INDEXCONTRASTSECTOR'

    OBJECT_ID = Column(String(100), primary_key=True, doc="对象ID")
    OPDATE = Column(DateTime)
    OPMODE = Column(String(1))
    S_INFO_INDEXCODE = Column(String(40), doc="指数万得代码")
    S_INFO_INDUSTRYCODE = Column(String(16), doc="板块代码")
    S_INFO_INDUSTRYCODE2 = Column(String(16), doc="板块代码2")
    S_INFO_INDUSTRYNAME = Column(String(50), doc="板块名称")
    S_INFO_INDUSTRYNAME_ENG = Column(String(200), doc="板块英文名称")
    S_INFO_NAME = Column(String(50), doc="指数简称")


class_dict = {
    'ASHAREBALANCESHEET': ASHAREBALANCESHEET,
    'ASHARECAPITALIZATION': ASHARECAPITALIZATION,
    'ASHARECASHFLOW': ASHARECASHFLOW,
    'ASHAREDESCRIPTION': ASHAREDESCRIPTION,
    'ASHAREDIVIDEND': ASHAREDIVIDEND,
    'ASHAREFINANCIALINDICATOR': ASHAREFINANCIALINDICATOR,
    'ASHAREFREEFLOAT': ASHAREFREEFLOAT,
    'ASHAREINCOME': ASHAREINCOME,
    'ASHAREINDUSTRIESCODE': ASHAREINDUSTRIESCODE,
    'ASHAREPROFITEXPRESS': ASHAREPROFITEXPRESS,
    'ASHARERIGHTISSUE': ASHARERIGHTISSUE,
    'CFUNDWINDINDEXCOMPONENT': CFUNDWINDINDEXCOMPONENT,
    'CHINAMUTUALFUNDASSETPORTFOLIO': CHINAMUTUALFUNDASSETPORTFOLIO,
    'CHINAMUTUALFUNDNAV': CHINAMUTUALFUNDNAV,
    'CHINAMUTUALFUNDREPNAVPER': CHINAMUTUALFUNDREPNAVPER,
    'CHINAMUTUALFUNDSEATTRADING': CHINAMUTUALFUNDSEATTRADING,
    'CMFINDUSTRYPLATE': CMFINDUSTRYPLATE,
    'CMFIOPVNAV': CMFIOPVNAV,
    'CMFNAVOPERATIONRECORD': CMFNAVOPERATIONRECORD,
    'CMFTHEMECONCEPT': CMFTHEMECONCEPT,
    'COMPINTRODUCTION': COMPINTRODUCTION,
    'INDEXCONTRASTSECTOR': INDEXCONTRASTSECTOR,
}
